.\" Written by Ralf Baechle (ralf@waldorf-gmbh.de),
.\" Copyright (c) 1994, 1995 Waldorf GMBH
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.TH CACHEFLUSH 2 1995-06-27 "Linux 2.0.32" "Linux Programmer's Manual"
.SH NAME
cacheflush \- flush contents of instruction and/or data cache
.SH SYNOPSIS
.nf
.B #include <asm/cachectl.h>
.sp
.BI "int cacheflush(char *" addr ", int "nbytes ", int "cache );
.fi
.SH DESCRIPTION
.B cacheflush
flushes contents of indicated cache(s) for user addresses in the range
addr to (addr+nbytes-1). Cache may be one of:
.TP
.B ICACHE
Flush the instruction cache.
.TP
.B DCACHE
Write back to memory and invalidate the affected valid cache lines.
.TP
.B BCACHE
Same as 
.B (ICACHE|DCACHE).
.PP
.SH "RETURN VALUE"
.B cacheflush
returns 0 on success or \-1 on error. If errors are detected,
errno will indicate the error.
.SH ERRORS
.TP
.B EFAULT
Some or all of the address range addr to (addr+nbytes-1) is not accessible.
.TP
.B EINVAL
cache parameter is not one of ICACHE, DCACHE, or BCACHE.
.PP
.SH BUGS
The current implementation ignores the addr and nbytes parameters.  Therefore
always the whole cache is flushed.
.SH NOTE
This system call is only available on MIPS based systems.  It should
not be used in programs intended to be portable.
