.\"
.\"  epoll by Davide Libenzi ( efficient event notification retrieval )
.\"  Copyright (C) 2003  Davide Libenzi
.\"
.\"  This program is free software; you can redistribute it and/or modify
.\"  it under the terms of the GNU General Public License as published by
.\"  the Free Software Foundation; either version 2 of the License, or
.\"  (at your option) any later version.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with this program; if not, write to the Free Software
.\"  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.\"  Davide Libenzi <davidel@xmailserver.org>
.\"
.\" Modified 2004-06-17 by Michael Kerrisk <mtk16@ext.canterbury.ac.nz>
.\"
.TH EPOLL_CREATE 2 "2004-06-17" "Linux 2.6.7" "Linux Programmer's Manual"
.SH NAME
epoll_create \- open an epoll file descriptor
.SH SYNOPSIS
.B #include <sys/epoll.h>
.sp
.BR "int epoll_create(int " size )
.SH DESCRIPTION
Open an
.B epoll
file descriptor by requesting the kernel allocate
an event backing store dimensioned for
.I size
descriptors. The
.I size
is not the maximum size of the backing store but
just a hint to the kernel about how to dimension internal structures.
The returned file descriptor will be used for all the subsequent calls to the
.B epoll
interface. The file descriptor returned by
.BR epoll_create (2)
must be closed by using
.BR close (2).
.SH "RETURN VALUE"
When successful,
.BR epoll_create (2)
returns a positive integer identifying the descriptor.
When an error occurs, 
.BR epoll_create (2)
returns -1 and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B ENFILE
The system limit on the total number of open files has been reached.
.TP
.B ENOMEM
There was insufficient memory to create the kernel object.
.SH CONFORMING TO
.BR epoll_create (2)
is a new API introduced in Linux kernel 2.5.44.
The interface should be finalized by Linux kernel 2.5.66.
.SH "SEE ALSO"
.BR close (2),
.BR epoll_ctl (2),
.BR epoll_wait (2),
.BR epoll (4)
