.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified 1997-08-25 by Nicolás Lichtmaier <nick@debian.org>
.\" Modified 2004-06-17 by Michael Kerrisk <mtk16@ext.canterbury.ac.nz>
.\"
.TH GETDOMAINNAME 2 2004-06-17 "Linux 2.6.7" "Linux Programmer's Manual"
.SH NAME
getdomainname, setdomainname \- get/set domain name
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.BI "int getdomainname(char *" name ", size_t " len );
.br
.BI "int setdomainname(const char *" name ", size_t " len );
.SH DESCRIPTION
These functions are used to access or to change the domain name of the
current processor.
If the NUL-terminated domain name requires more than \fIlen\fP bytes,
.B getdomainname
returns the first \fIlen\fP bytes (glibc) or returns an error (libc).
.SH "RETURN VALUE"
On success, zero is returned.  On error, \-1 is returned, and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EFAULT
For
.BR setdomainname :
.I name
pointed outside of user address space.
.TP
.B EINVAL
For
.BR getdomainname
under libc:
.I name
is
.B NULL
or
.I name
is longer than
.I len
bytes.
.TP
.B EINVAL
For
.BR setdomainname :
.I len
was negative or too large.
.TP
.B EPERM
For
.BR setdomainname :
the caller is unprivileged (Linux: does not have the
.B CAP_SYS_ADMIN
capability).
.SH "CONFORMING TO"
POSIX does not specify these calls.
.SH "SEE ALSO"
.BR gethostname (2),
.BR sethostname (2),
.BR uname (2)
