.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Updated with additions from Mitchum DSouza <m.dsouza@mrc-apu.cam.ac.uk>
.\" Portions Copyright 1993 Mitchum DSouza <m.dsouza@mrc-apu.cam.ac.uk>
.\"
.\" Modified Tue Oct 22 00:22:35 EDT 1996 by Eric S. Raymond <esr@thyrsus.com>
.TH GETHOSTID 2 1993-11-29 "Linux 0.99.13" "Linux Programmer's Manual"
.SH NAME
gethostid, sethostid \- get or set the unique identifier of the current host
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.B long gethostid(void);
.br
.BI "int sethostid(long " hostid );
.SH DESCRIPTION
Get or set a unique 32-bit identifier for the current machine.  The 32-bit
identifier is intended to be unique among all UNIX systems in
existence. This normally resembles the Internet address for the local
machine, as returned by
.BR gethostbyname (3),
and thus usually never needs to be set.

The
.B sethostid
call is restricted to the superuser.

The
.I hostid
argument is stored in the file
.IR /etc/hostid .
.SH "RETURN VALUE"
.B gethostid
returns the 32-bit identifier for the current host as set by
.BR sethostid (2).
.SH "CONFORMING TO"
4.2BSD.  These functions were dropped in 4.4BSD.
POSIX.1 does not define these functions, but ISO/IEC 9945-1:1990 mentions
them in B.4.4.1.  SVr4 includes 
.B gethostid
but not
.BR sethostid .
.SH FILES
.I /etc/hostid
.SH "SEE ALSO"
.BR hostid (1),
.BR gethostbyname (3)
