.\" Copyright (C) 2003 Free Software Foundation, Inc.
.\" This file is distributed according to the GNU General Public License.
.\" See the file COPYING in the top level source directory for details.
.\"
.de Sh \" Subsection
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.de Ip \" List item
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.TH "IO_DESTROY" 2 "2003-02-21" "Linux 2.4" "Linux Programmer's Manual"
.SH NAME
io_destroy \- Destroy an asynchronous I/O context
.SH "SYNOPSIS"
.ad l
.hy 0

#include <linux/aio.h>
.sp
.HP 17
long\ \fBio_destroy\fR\ (aio_context_t\ \fIctx\fR);
.ad
.hy

.SH "DESCRIPTION"

.PP
\fBio_destroy\fR removes the asynchronous I/O context from the list of 
I/O contexts and then destroys it. 
\fBio_destroy\fR can also cancel any outstanding asynchronous I/O 
actions on \fIctx\fR and block on completion.

.SH "RETURN VALUE"

.PP
\fBio_destroy\fR returns 0 on success.

.SH "ERRORS"

.TP
EINVAL
The AIO context specified by \fIctx\fR is invalid.

.TP
EFAULT
The context pointed to is invalid.

.TP
ENOSYS
\fBio_destroy\fR is not implemented on this architecture.

.SH "CONFORMING TO"

.PP
\fBio_destroy\fR is Linux specific and should not be used in programs 
that are intended to be portable.

.SH "VERSIONS"

.PP
The asynchronous I/O system calls first appeared in Linux 2.5, August 2002.

.SH "SEE ALSO"

.PP
\fBio_setup\fR(2), \fBio_submit\fR(2), \fBio_getevents\fR(2), \fBio_cancel\fR(2).

.SH "NOTES"

.PP
The asynchronous I/O system calls were written by Benjamin LaHaise.

.SH AUTHOR
Kent Yoder.
