.\" Copyright (C) 1995, Thomas K. Dyas <tdyas@eden.rutgers.edu>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Created   Sat Aug 21 1995     Thomas K. Dyas <tdyas@eden.rutgers.edu>
.\"
.\" typo corrected, aeb, 950825
.\" added layout change from joey, 960722
.\" changed prototype, documented 0xffffffff, aeb, 030101
.\" Modified 2004-11-03 patch from Martin Schulze <joey@infodrom.org>
.\"
.TH PERSONALITY 2 2003-01-01 "Linux" "Linux Programmer's Manual"
.SH NAME
personality \- set the process execution domain
.SH SYNOPSIS
.B #include <sys/personality.h>
.sp
.BI "int personality(unsigned long " persona );
.SH DESCRIPTION
Linux supports different execution domains, or personalities, for each
process.
Among other things, execution domains tell Linux how to map
signal numbers into signal actions.
The execution domain system allows
Linux to provide limited support for binaries compiled under other
UNIX-like operating systems.

This function will return the current
.BR personality ()
when
.I persona
equals 0xffffffff.
Otherwise, it will make the execution domain
referenced by
.I persona
the new execution domain of the calling process.
.SH "RETURN VALUE"
On success, the previous
.I persona
is returned.
On error, \-1 is returned, and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EINVAL
The kernel was unable to change the personality.
.SH "CONFORMING TO"
.BR personality ()
is Linux-specific and should not be used in programs intended to
be portable.
