.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1995 Michael Chastain (mec@shell.portal.com), 15 April 1995.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Updated, aeb, 980612
.\"
.TH UNIMPLEMENTED 2 2003-02-28 "Linux 2.4" "Linux Programmer's Manual"
.SH NAME
afs_syscall, break, ftime, getpmsg, gtty, lock, mpx, prof, profil,
putpmsg, security, stty, ulimit \- unimplemented system calls
.SH SYNOPSIS
Unimplemented system calls.
.SH DESCRIPTION
These system calls are not implemented in the Linux 2.4 kernel.
.SH "RETURN VALUE"
These system calls always return \-1 and set
.I errno
to
.BR ENOSYS .
.SH NOTES
Note that
.IR ftime (3),
.IR profil (3)
and
.IR ulimit (3)
are implemented as library functions.

Some system calls, like
.IR alloc_hugepages (2),
.IR free_hugepages (2),
.IR ioperm (2),
.IR iopl (2),
and
.IR vm86 (2)
only exist on certain architectures.

Some system calls, like
.IR ipc (2)
and
.IR {create,init,delete}_module (2)
only exist when the Linux kernel was built with support for them.

.SH "SEE ALSO"
.BR obsolete (2)
