'\" t -*- coding: ARMSCII-8 -*-
.\" Copyright 2009  Lefteris Dimitroulakis <edimitro at tee.gr>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\"
.TH ARMSCII-8 7 2009-01-21 "Linux" "Linux Programmer's Manual"
.nh
.SH NAME
armscii-8 \- Armenian Character Set encoded in octal, decimal, and
hexadecimal
.SH DESCRIPTION
The Armenian Standard Code for Information Interchange,
8-bit coded character set.
.SS "ARMSCII-8 Characters"
The following table displays the characters in ARMSCII-8, which
are printable and unlisted in the
.BR ascii (7)
manual page.
The fourth column will only show the proper glyphs
in an environment configured for armscii-8.
.TS
l l l c lp-1.
Oct	Dec	Hex	Char	Description
_
240	160	a0	 	NO-BREAK SPACE
242	162	a2	¢	ARMENIAN SMALL LIGATURE ECH YIWN
243	163	a3	£	ARMENIAN FULL STOP
244	164	a4	)	RIGHT PARENTHESIS
245	165	a5	(	LEFT PARENTHESIS
246	166	a6	¦	RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
247	167	a7	§	LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
250	168	a8	¨	EM DASH
251	169	a9	.	FULL STOP
252	170	aa	ª	ARMENIAN COMMA
253	171	ab	,	COMMA
254	172	ac	-	HYPHEN-MINUS
255	173	ad	­	ARMENIAN HYPHEN
256	174	ae	®	HORIZONTAL ELLIPSIS
257	175	af	¯	ARMENIAN EXCLAMATION MARK
260	176	b0	°	ARMENIAN EMPHASIS MARK
261	177	b1	±	ARMENIAN QUESTION MARK
262	178	b2	²	ARMENIAN CAPITAL LETTER AYB
263	179	b3	³	ARMENIAN SMALL LETTER AYB
264	180	b4	´	ARMENIAN CAPITAL LETTER BEN
265	181	b5	µ	ARMENIAN SMALL LETTER BEN
266	182	b6	¶	ARMENIAN CAPITAL LETTER GIM
267	183	b7	·	ARMENIAN SMALL LETTER GIM
270	184	b8	¸	ARMENIAN CAPITAL LETTER DA
271	185	b9	¹	ARMENIAN SMALL LETTER DA
272	186	ba	º	ARMENIAN CAPITAL LETTER ECH
273	187	bb	»	ARMENIAN SMALL LETTER ECH
274	188	bc	¼	ARMENIAN CAPITAL LETTER ZA
275	189	bd	½	ARMENIAN SMALL LETTER ZA
276	190	be	¾	ARMENIAN CAPITAL LETTER EH
277	191	bf	¿	ARMENIAN SMALL LETTER EH
300	192	c0	À	ARMENIAN CAPITAL LETTER ET
301	193	c1	Á	ARMENIAN SMALL LETTER ET
302	194	c2	Â	ARMENIAN CAPITAL LETTER TO
303	195	c3	Ã	ARMENIAN SMALL LETTER TO
304	196	c4	Ä	ARMENIAN CAPITAL LETTER ZHE
305	197	c5	Å	ARMENIAN SMALL LETTER ZHE
306	198	c6	Æ	ARMENIAN CAPITAL LETTER INI
307	199	c7	Ç	ARMENIAN SMALL LETTER INI
310	200	c8	È	ARMENIAN CAPITAL LETTER LIWN
311	201	c9	É	ARMENIAN SMALL LETTER LIWN
312	202	ca	Ê	ARMENIAN CAPITAL LETTER XEH
313	203	cb	Ë	ARMENIAN SMALL LETTER XEH
314	204	cc	Ì	ARMENIAN CAPITAL LETTER CA
315	205	cd	Í	ARMENIAN SMALL LETTER CA
316	206	ce	Î	ARMENIAN CAPITAL LETTER KEN
317	207	cf	Ï	ARMENIAN SMALL LETTER KEN
320	208	d0	Ð	ARMENIAN CAPITAL LETTER HO
321	209	d1	Ñ	ARMENIAN SMALL LETTER HO
322	210	d2	Ò	ARMENIAN CAPITAL LETTER JA
323	211	d3	Ó	ARMENIAN SMALL LETTER JA
324	212	d4	Ô	ARMENIAN CAPITAL LETTER GHAD
325	213	d5	Õ	ARMENIAN SMALL LETTER GHAD
326	214	d6	Ö	ARMENIAN CAPITAL LETTER CHEH
327	215	d7	×	ARMENIAN SMALL LETTER CHEH
330	216	d8	Ø	ARMENIAN CAPITAL LETTER MEN
331	217	d9	Ù	ARMENIAN SMALL LETTER MEN
332	218	da	Ú	ARMENIAN CAPITAL LETTER YI
333	219	db	Û	ARMENIAN SMALL LETTER YI
334	219	dc	Ü	ARMENIAN CAPITAL LETTER NOW
335	220	dd	Ý	ARMENIAN SMALL LETTER NOW
336	221	de	Þ	ARMENIAN CAPITAL LETTER SHA
337	222	df	ß	ARMENIAN SMALL LETTER SHA
340	223	e0	à	ARMENIAN CAPITAL LETTER VO
341	224	e1	á	ARMENIAN SMALL LETTER VO
342	225	e2	â	ARMENIAN CAPITAL LETTER CHA
343	226	e3	ã	ARMENIAN SMALL LETTER CHA
344	227	e4	ä	ARMENIAN CAPITAL LETTER PEH
345	228	e5	å	ARMENIAN SMALL LETTER PEH
346	229	e6	æ	ARMENIAN CAPITAL LETTER JHEH
347	230	e7	ç	ARMENIAN SMALL LETTER JHEH
350	231	e8	è	ARMENIAN CAPITAL LETTER RA
351	232	e9	é	ARMENIAN SMALL LETTER RA
352	233	ea	ê	ARMENIAN CAPITAL LETTER SEH
353	234	eb	ë	ARMENIAN SMALL LETTER SEH
354	235	ec	ì	ARMENIAN CAPITAL LETTER VEW
355	236	ed	í	ARMENIAN SMALL LETTER VEW
356	237	ee	î	ARMENIAN CAPITAL LETTER TIWN
357	238	ef	ï	ARMENIAN SMALL LETTER TIWN
360	239	f0	ð	ARMENIAN CAPITAL LETTER REH
361	240	f1	ñ	ARMENIAN SMALL LETTER REH
362	241	f2	ò	ARMENIAN CAPITAL LETTER CO
363	242	f3	ó	ARMENIAN SMALL LETTER CO
364	243	f4	ô	ARMENIAN CAPITAL LETTER YIWN
365	244	f5	õ	ARMENIAN SMALL LETTER YIWN
366	245	f6	ö	ARMENIAN CAPITAL LETTER PIWR
367	246	f7	÷	ARMENIAN SMALL LETTER PIWR
370	247	f8	ø	ARMENIAN CAPITAL LETTER KEH
371	248	f9	ù	ARMENIAN SMALL LETTER KEH
372	249	fa	ú	ARMENIAN CAPITAL LETTER OH
373	250	fb	û	ARMENIAN SMALL LETTER OH
374	251	fc	ü	ARMENIAN CAPITAL LETTER FEH
375	252	fd	ý	ARMENIAN SMALL LETTER FEH
376	253	fe	þ	ARMENIAN APOSTROPHE
.TE
.SH "SEE ALSO"
.BR ascii (7)

