'\" t -*- coding: CP1251 -*-
.\" Copyright 2009    Lefteris Dimitroulakis (edimitro@tee.gr)
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.TH CP1251 7 2010-09-20 "Linux" "Linux Programmer's Manual"
.SH NAME
cp1251 \- CP\ 1251 character set encoded in octal, decimal,
and hexadecimal
.SH DESCRIPTION
The Windows Code Pages include several 8-bit extensions to the ASCII
character set (also known as ISO 646-IRV).
CP\ 1251 encodes the characters used in Cyrillic scripts.
.\" (In my system with glibc-2.8-20080929
.\" I found only bg_BG and be_BY locales using this encoding).
The following table displays the characters in CP\ 1251, which
are printable and unlisted in the
.BR ascii (7)
manual page.
The fourth column will only show the proper glyphs
in an environment configured for CP\ 1251.
.TS
l2 l2 l2 c2 lp-1.
Oct	Dec	Hex	Char	Description
_
200	128	80	Ä	CYRILLIC CAPITAL LETTER DJE
201	129	81	Å	CYRILLIC CAPITAL LETTER GJE
202	130	82	Ç	SINGLE LOW-9 QUOTATION MARK
203	131	83	É	CYRILLIC SMALL LETTER GJE
204	132	84	Ñ	DOUBLE LOW-9 QUOTATION MARK
205	133	85	Ö	HORIZONTAL ELLIPSIS
206	134	86	Ü	DAGGER
207	135	87	á	DOUBLE DAGGER
210	136	88	à	EURO SIGN
211	137	89	â	PER MILLE SIGN
212	138	8A	ä	CYRILLIC CAPITAL LETTER LJE
213	139	8B	ã	SINGLE LEFT-POINTING ANGLE QUOTATION MARK
214	140	8C	å	CYRILLIC CAPITAL LETTER NJE
215	141	8D	ç	CYRILLIC CAPITAL LETTER KJE
216	142	8E	é	CYRILLIC CAPITAL LETTER TSHE
217	143	8F	è	CYRILLIC CAPITAL LETTER DZHE
220	144	90	ê	CYRILLIC SMALL LETTER DJE
221	145	91	ë	LEFT SINGLE QUOTATION MARK
222	146	92	í	RIGHT SINGLE QUOTATION MARK
223	147	93	ì	LEFT DOUBLE QUOTATION MARK
224	148	94	î	RIGHT DOUBLE QUOTATION MARK
225	149	95	ï	BULLET
226	150	96	ñ	EN DASH
227	151	97	ó	EM DASH
230	152	98	 	UNDEFINED
231	153	99	ô	TRADE MARK SIGN
232	154	9A	ö	CYRILLIC SMALL LETTER LJE
233	155	9B	õ	SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
234	156	9C	ú	CYRILLIC SMALL LETTER NJE
235	157	9D	ù	CYRILLIC SMALL LETTER KJE
236	158	9E	û	CYRILLIC SMALL LETTER TSHE
237	159	9F	ü	CYRILLIC SMALL LETTER DZHE
240	160	A0	†	NO-BREAK SPACE
241	161	A1	°	CYRILLIC CAPITAL LETTER SHORT U
242	162	A2	¢	CYRILLIC SMALL LETTER SHORT U
243	163	A3	£	CYRILLIC CAPITAL LETTER JE
244	164	A4	§	CURRENCY SIGN
245	165	A5	•	CYRILLIC CAPITAL LETTER GHE WITH UPTURN
246	166	A6	¶	BROKEN BAR
247	167	A7	ß	SECTION SIGN
250	168	A8	®	CYRILLIC CAPITAL LETTER IO
251	169	A9	©	COPYRIGHT SIGN
252	170	AA	™	CYRILLIC CAPITAL LETTER UKRAINIAN IE
253	171	AB	´	LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
254	172	AC	¨	NOT SIGN
255	173	AD	≠	SOFT HYPHEN
256	174	AE	Æ	REGISTERED SIGN
257	175	AF	Ø	CYRILLIC CAPITAL LETTER YI
260	176	B0	∞	DEGREE SIGN
261	177	B1	±	PLUS-MINUS SIGN
262	178	B2	≤	CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
263	179	B3	≥	CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
264	180	B4	¥	CYRILLIC SMALL LETTER GHE WITH UPTURN
265	181	B5	µ	MICRO SIGN
266	182	B6	∂	PILCROW SIGN
267	183	B7	∑	MIDDLE DOT
270	184	B8	∏	CYRILLIC SMALL LETTER IO
271	185	B9	π	NUMERO SIGN
272	186	BA	∫	CYRILLIC SMALL LETTER UKRAINIAN IE
273	187	BB	ª	RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
274	188	BC	º	CYRILLIC SMALL LETTER JE
275	189	BD	Ω	CYRILLIC CAPITAL LETTER DZE
276	190	BE	æ	CYRILLIC SMALL LETTER DZE
277	191	BF	ø	CYRILLIC SMALL LETTER YI
300	192	C0	¿	CYRILLIC CAPITAL LETTER A
301	193	C1	¡	CYRILLIC CAPITAL LETTER BE
302	194	C2	¬	CYRILLIC CAPITAL LETTER VE
303	195	C3	√	CYRILLIC CAPITAL LETTER GHE
304	196	C4	ƒ	CYRILLIC CAPITAL LETTER DE
305	197	C5	≈	CYRILLIC CAPITAL LETTER IE
306	198	C6	∆	CYRILLIC CAPITAL LETTER ZHE
307	199	C7	v	CYRILLIC CAPITAL LETTER ZE
310	200	C8	»	CYRILLIC CAPITAL LETTER I
311	201	C9	…	CYRILLIC CAPITAL LETTER SHORT I
312	202	CA	 	CYRILLIC CAPITAL LETTER KA
313	203	CB	À	CYRILLIC CAPITAL LETTER EL
314	204	CC	Ã	CYRILLIC CAPITAL LETTER EM
315	205	CD	Õ	CYRILLIC CAPITAL LETTER EN
316	206	CE	Œ	CYRILLIC CAPITAL LETTER O
317	207	CF	œ	CYRILLIC CAPITAL LETTER PE
320	208	D0	–	CYRILLIC CAPITAL LETTER ER
321	209	D1	—	CYRILLIC CAPITAL LETTER ES
322	210	D2	“	CYRILLIC CAPITAL LETTER TE
323	211	D3	”	CYRILLIC CAPITAL LETTER U
324	212	D4	‘	CYRILLIC CAPITAL LETTER EF
325	213	D5	’	CYRILLIC CAPITAL LETTER HA
326	214	D6	÷	CYRILLIC CAPITAL LETTER TSE
327	215	D7	◊	CYRILLIC CAPITAL LETTER CHE
330	216	D8	ÿ	CYRILLIC CAPITAL LETTER SHA
331	217	D9	Ÿ	CYRILLIC CAPITAL LETTER SHCHA
332	218	DA	⁄	CYRILLIC CAPITAL LETTER HARD SIGN
333	219	DB	€	CYRILLIC CAPITAL LETTER YERU
334	220	DC	‹	CYRILLIC CAPITAL LETTER SOFT SIGN
335	221	DD	›	CYRILLIC CAPITAL LETTER E
336	222	DE	ﬁ	CYRILLIC CAPITAL LETTER YU
337	223	DF	ﬂ	CYRILLIC CAPITAL LETTER YA
340	224	E0	‡	CYRILLIC SMALL LETTER A
341	225	E1	·	CYRILLIC SMALL LETTER BE
342	226	E2	‚	CYRILLIC SMALL LETTER VE
343	227	E3	„	CYRILLIC SMALL LETTER GHE
344	228	E4	‰	CYRILLIC SMALL LETTER DE
345	229	E5	Â	CYRILLIC SMALL LETTER IE
346	230	E6	Ê	CYRILLIC SMALL LETTER ZHE
347	231	E7	Á	CYRILLIC SMALL LETTER ZE
350	232	E8	Ë	CYRILLIC SMALL LETTER I
351	233	E9	È	CYRILLIC SMALL LETTER SHORT I
352	234	EA	Í	CYRILLIC SMALL LETTER KA
353	235	EB	Î	CYRILLIC SMALL LETTER EL
354	236	EC	Ï	CYRILLIC SMALL LETTER EM
355	237	ED	Ì	CYRILLIC SMALL LETTER EN
356	238	EE	Ó	CYRILLIC SMALL LETTER O
357	239	EF	Ô	CYRILLIC SMALL LETTER PE
360	240	F0		CYRILLIC SMALL LETTER ER
361	241	F1	Ò	CYRILLIC SMALL LETTER ES
362	242	F2	Ú	CYRILLIC SMALL LETTER TE
363	243	F3	Û	CYRILLIC SMALL LETTER U
364	244	F4	Ù	CYRILLIC SMALL LETTER EF
365	245	F5	ı	CYRILLIC SMALL LETTER HA
366	246	F6	ˆ	CYRILLIC SMALL LETTER TSE
367	247	F7	˜	CYRILLIC SMALL LETTER CHE
370	248	F8	¯	CYRILLIC SMALL LETTER SHA
371	249	F9	˘	CYRILLIC SMALL LETTER SHCHA
372	250	FA	˙	CYRILLIC SMALL LETTER HARD SIGN
373	251	FB	˚	CYRILLIC SMALL LETTER YERU
374	252	FC	¸	CYRILLIC SMALL LETTER SOFT SIGN
375	253	FD	˝	CYRILLIC SMALL LETTER E
376	254	FE	˛	CYRILLIC SMALL LETTER YU
377	255	FF	ˇ	CYRILLIC SMALL LETTER YA
.TE
.SH NOTES
CP\ 1251 is also known as Windows Cyrillic.
.SH SEE ALSO
.BR ascii (7)
