.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CACOS 3 2002-07-28 "" "complex math routines"
.SH NAME
cacos, cacosf, cacosl \- complex arc cosine
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cacos(double complex " z ); 
.sp
.BI "float complex cacosf(float complex " z ); 
.sp
.BI "long double complex cacosl(long double complex " z ); 
.sp
Link with \-lm.
.SH DESCRIPTION
The cacos() function calculates the complex acos().
If y = cacos(z), then z = ccos(y).
The real part of y is chosen in the interval [0,pi].
.LP
One has cacos(z) = -i clog(z+csqrt(z*z-1)).
.SH "CONFORMING TO"
C99
.SH "SEE ALSO"
.BR ccos (3),
.BR clog (3),
.BR complex (5)
