.\" Copyright 2002 Walter Harms(walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CACOSH 3 2002-07-28 "" "complex math routines"
.SH NAME
cacosh, cacoshf, cacoshl \- complex arc hyperbolic cosine
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cacosh(double complex " z ); 
.sp
.BI "float complex cacoshf(float complex " z );
.sp
.BI "long double complex cacoshl(long double complex " z );
.sp
Link with \-lm.
.SH DESCRIPTION
The cacosh() function calculates the complex acosh().
If y = cacosh(z), then z = ccosh(y).
The imaginary part of y is chosen in the interval [-pi,pi].
The real part of y is chosen nonnegative.
.LP
One has cacosh(z) = (0.5)*clog((1+z)/(1-z)).
.SH "CONFORMING TO"
C99
.SH "SEE ALSO"
.BR acosh (3),
.BR cabs (3),
.BR cimag (3),
.BR complex (5)
