.\" Copyright 1995 Jim Van Zandt <jrv@vanzandt.mv.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" changed `square root' into `cube root' - aeb, 950919
.\"
.\" Modified 2002-07-27 Walter Harms
.\" (walter.harms@informatik.uni-oldenburg.de)
.\"
.TH CBRT 3  2002-27-07 "GNU"  "Linux Programmer's Manual"
.SH NAME
cbrt, cbrtf, cbrtl \- cube root function
.SH SYNOPSIS
.nf
.B #include <math.h>
.sp
.BI "double cbrt(double " x );
.br
.BI "float cbrtf(float " x );
.br
.BI "long double cbrtl(long double " x );
.fi
.sp
Link with \-lm.
.SH DESCRIPTION
The \fBcbrt()\fP function returns the (real) cube root of \fIx\fP.
This function cannot fail; every representable real value has a
representable real cube root.
.SH "CONFORMING TO"
.B cbrt()
was a GNU extension. It is now a C99 requirement.
.SH "SEE ALSO"
.BR pow (3),
.BR sqrt (3)
