.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CEXP 3 2002-07-28 "" "complex math routines"
.SH NAME
cexp, cexpf, cexpl \- complex exponential function
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cexp(double complex " z ");"
.sp
.BI "float complex cexpf(float complex " z ");"
.sp
.BI "long double complex cexpl(long double complex " z ");"
.sp
Link with \-lm.
.SH DESCRIPTION
The function calculates e (2.71828..., the base of natural logarithms)
raised to the power of z.
.LP
One has cexp(I*z) = ccos(z) + I*csin(z).
.SH "CONFORMING TO"
C99
.SH "SEE ALSO"
.BR cabs (3),
.BR clog (3),
.BR cpow (3),
.BR complex (5)
