.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CEXP 3 2008-08-11 "" "Linux Programmer's Manual"
.SH NAME
cexp, cexpf, cexpl \- complex exponential function
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cexp(double complex " z ");"
.br
.BI "float complex cexpf(float complex " z ");"
.br
.BI "long double complex cexpl(long double complex " z ");"
.sp
Link with \fI\-lm\fP.
.SH DESCRIPTION
The function calculates e (2.71828..., the base of natural logarithms)
raised to the power of
.IR z .
.LP
One has:
.nf

    cexp(I * z) = ccos(z) + I * csin(z)
.fi
.SH VERSIONS
These functions first appeared in glibc in version 2.1.
.SH CONFORMING TO
C99.
.SH SEE ALSO
.BR cabs (3),
.BR cexp2 (3),
.BR clog (3),
.BR cpow (3),
.BR complex (7)
