.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CLOG 3 2002-07-28 "" "complex math routines"
.SH NAME
clog, clogf, clogl \- natural logarithm of a complex number
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex clog(double complex " z );
.sp
.BI "float complex clogf(float complex " z );
.sp
.BI "long double complex clogl(long double complex " z );
.sp
Link with \-lm.
.SH DESCRIPTION
The logarithm clog is the inverse function of the exponential cexp.
Thus, if y = clog(z), then z = cexp(y).
The imaginary part of y is chosen in the interval [-pi,pi].
.LP
One has clog(z) = log(cabs(z))+I*carg(z).
.LP
Please note that z close to zero will cause an overflow. 
.SH "CONFORMING TO"
C99
.SH "SEE ALSO"
.BR cabs (3),
.BR cexp (3),
.BR clog10 (3),
.BR complex (5)
