.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" %%%LICENSE_START(GPL_NOVERSION_ONELINE)
.\" Distributed under GPL
.\" %%%LICENSE_END
.\"
.TH CLOG10 3 2008-08-11 "" "Linux Programmer's Manual"
.SH NAME
clog10, clog10f, clog10l \- base-10 logarithm of a complex number
.SH SYNOPSIS
.BR "#define _GNU_SOURCE" "         /* See feature_test_macros(7) */"
.br
.B #include <complex.h>
.sp
.BI "double complex clog10(double complex " z );
.br
.BI "float complex clog10f(float complex " z );
.br
.BI "long double complex clog10l(long double complex " z );
.sp
Link with \fI\-lm\fP.
.SH DESCRIPTION
The call
.I clog10(z)
is equivalent to
.IR clog(z)/log(10) .
The other functions perform the same task for
.I float
and
.IR "long double" .

Note that
.I z
close to zero will cause an overflow.
.SH VERSIONS
These functions first appeared in glibc in version 2.1.
.SH CONFORMING TO
This function is a GNU extension.
It is reserved for future use in C99.
.SH SEE ALSO
.BR cabs (3),
.BR cexp (3),
.BR clog (3),
.BR clog2 (3),
.BR complex (7)
