.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CPROJ 3 2010-06-10 "" "Linux Programmer's Manual"
.SH NAME
cproj, cprojf, cprojl \- project into Riemann Sphere
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cproj(double complex " z ");"
.br
.BI "float complex cprojf(float complex " z ");"
.br
.BI "long double complex cprojl(long double complex " z ");"
.sp
Link with \fI\-lm\fP.
.SH DESCRIPTION
This function projects a point in the plane onto the surface of a
Riemann Sphere, the one-point compactification of the complex plane.
Each finite point
.I z
projects to
.I z
itself.
Every complex infinite value is projected to a single infinite value,
namely to positive infinity on the real axis.
.SH VERSIONS
These functions first appeared in glibc in version 2.1.
.SH CONFORMING TO
C99.
.SH NOTES
In glibc 2.11 and earlier, the implementation does something different
(a \fIstereographic\fP projection onto a Riemann Sphere).
.\" http://sources.redhat.com/bugzilla/show_bug.cgi?id=10401
.SH SEE ALSO
.BR cabs (3),
.BR complex (7)
