.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\"
.\" %%%LICENSE_START(GPL_NOVERSION_ONELINE)
.\" Distributed under GPL
.\" %%%LICENSE_END
.\"
.TH CSQRT 3 2008-08-11 "" "Linux Programmer's Manual"
.SH NAME
csqrt, csqrtf, csqrtl \- complex square root
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex csqrt(double complex " z ");"
.br
.BI "float complex csqrtf(float complex " z ");"
.br
.BI "long double complex csqrtl(long double complex " z ");"
.sp
Link with \fI\-lm\fP.
.SH DESCRIPTION
Calculate the square root of a given complex number,
with nonnegative real part, and
with a branch cut along the negative real axis.
(That means that \fIcsqrt(\-1+eps*I)\fP will be close to I while
\fIcsqrt(\-1\-eps*I)\fP will be close to \-I, \fIif eps\fP is a small positive
real number.)
.SH VERSIONS
These functions first appeared in glibc in version 2.1.
.SH CONFORMING TO
C99.
.SH SEE ALSO
.BR cabs (3),
.BR cexp (3),
.BR complex (7)
