.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CSQRT 3 2002-07-28 "" "complex math routines"
.SH NAME
csqrt, csqrtf, csqrtl \- complex square root
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex csqrt(double complex " z ");"
.sp
.BI "float complex csqrtf(float complex " z ");"
.sp
.BI "long double complex csqrtl(long double complex " z ");"
.sp
Link with \-lm.
.SH DESCRIPTION
Calculate the square root of a given complex number,
with nonnegative real part, and
with a branch cut along the negative real axis.
(That means that csqrt(-1+eps*I) will be close to I while
csqrt(-1-eps*I) will be close to -I, if eps is a small positive
real number.)
.SH "CONFORMING TO"
C99
.SH "SEE ALSO"
.BR cabs (3),
.BR cexp (3),
.BR complex (5)
