.\" Copyright 2001 Andries Brouwer <aeb@cwi.nl>.
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.TH FSEEKO 3  2001-11-05 "" "Linux Programmer's Manual"
.SH NAME
fseeko, ftello \- seek to or report file position
.SH SYNOPSIS
.nf
.B #include <stdio.h>
.sp
.BI "int fseeko(FILE *" stream ", off_t " offset ", int " whence );
.sp
.BI "off_t ftello(FILE *" stream );
.BI
.fi
.SH DESCRIPTION
The
.BR fseeko ()
and
.BR ftello ()
functions are identical to
.BR fseek (3)
and
.BR ftell (3)
(see
.BR fseek (3)),
respectively, except that the \fIoffset\fP argument of
.BR fseeko ()
and the return value of
.BR ftello ()
is of type \fIoff_t\fP
instead of \fIlong\fP.
.LP
On many architectures both \fIoff_t\fP and \fIlong\fP are 32-bit types,
but compilation with
.RS
.nf

#define _FILE_OFFSET_BITS 64
.fi
.RE
.PP
will turn \fIoff_t\fP into a 64-bit type.
.SH RETURN VALUE
On successful completion,
.BR fseeko ()
returns 0, while
.BR ftello ()
returns the current offset.
Otherwise, \-1 is returned and
.I errno
is set to indicate the error.
.SH ERRORS
See the ERRORS in
.BR fseek (3).
.SH CONFORMING TO
SUSv2, POSIX.1-2001.
.SH NOTES
These functions are found on System V-like systems.
They are not present in libc4, libc5, glibc 2.0
but are available since glibc 2.1.
.SH SEE ALSO
.BR fseek (3)
