.\" Copyright (c) 2012, Petr Benas
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided that
.\" the entire resulting derived work is distributed under the terms of
.\" a permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume.
.\" no responsibility for errors or omissions, or for damages resulting.
.\" from the use of the information contained herein.  The author(s) may.
.\" not have taken the same level of care in the production of this.
.\" manual, which is licensed free of charge, as they might when working.
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.

.TH GET_NPROCS 3   2012-03-20 "GNU" "Linux Programmer's Manual"
.SH NAME
get_nprocs, get_nprocs_conf \- get number of processors available /
configured by the operating system
.SH SYNOPSIS
.B #include <sys/sysinfo.h>
.sp
.BI "int get_nprocs(void);"
.br
.BI "int get_nprocs_conf(void);"
.SH DESCRIPTION
The function
.BR get_nprocs ()
returns the number of processors currently available in the system.
The number returned can be affected by CPU logical hotplug.
.sp
The function
.BR get_nprocs_conf ()
returns the number of processors configured by the operating system.
The number returned is not affected by CPU logical hotplug.
.SH EXAMPLE
Following is an example how
.BR get_nprocs ()
and
.BR get_nprocs_conf ()
can be used.

.nf
#include <stdio.h>
#include <sys/sysinfo.h>

int main(int argc, char *argv[])
{
    printf("This sytem has %d processors available and %d processors " \\
        "configured.\\n", get_nprocs(), get_nprocs_conf());
    return 0;
}
.fi

