.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:29:54 1993 by Rik Faith (faith@cs.unc.edu)
.TH GETGRENT 3  1993-04-04 "" "Linux Programmer's Manual"
.SH NAME
getgrent, setgrent, endgrent \- get group file entry
.SH SYNOPSIS
.nf
.B #include <sys/types.h>
.B #include <grp.h>
.sp
.B struct group *getgrent(void);
.sp
.B void setgrent(void);
.sp
.B void endgrent(void);
.fi
.SH DESCRIPTION
The \fBgetgrent()\fP function returns a pointer to a structure containing
the group information from \fI/etc/group\fP.  The first time it is called
it returns the first entry; thereafter, it returns successive entries.
.PP
The \fBsetgrent()\fP function rewinds the file pointer to the beginning 
of the \fI/etc/group\fP file.
.PP
The \fBendgrent()\fP function closes the \fI/etc/group\fP file.
.PP
The \fIgroup\fP structure is defined in \fI<grp.h>\fP as follows:
.sp
.RS
.nf
.ta 8n 16n 32n
struct group {
        char    *gr_name;        /* group name */
        char    *gr_passwd;      /* group password */
        gid_t   gr_gid;          /* group id */
        char    **gr_mem;        /* group members */
};
.ta
.fi
.RE
.SH "RETURN VALUE"
The \fBgetgrent()\fP function returns the group information structure, 
or NULL if there are no more entries or an error occurs.
.LP
Upon error,
.I errno
may be set. If you want to check its value, set it to zero before the call.
.SH ERRORS
.TP
.B EINTR
A signal was caught.
.TP
.B EIO
I/O error.
.TP
.B EMFILE
The calling process already has too many open files.
.TP
.B ENFILE
Too many open files in the system.
.TP
.\" not in POSIX
.B ENOMEM
Insufficient memory to allocate group information structure.
.SH FILES
.TP
.I /etc/group
 group database file
.SH "CONFORMING TO"
SVID 3, BSD 4.3, POSIX 1003.1-2003.
.SH "SEE ALSO"
.BR fgetgrent (3),
.BR getgrent_r (3),
.BR getgrgid (3),
.BR getgrnam (3)
