.\" Copyright (c) 1993 Michael Haardt (michael@moria.de), Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\" 
.\" Modified Sat Jul 24 17:38:23 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Thu Apr 20 20:43:53 1995 by Jim Van Zandt <jrv@vanzandt.mv.com>
.TH ISATTY 3 1995-04-20 "Linux" "Linux Programmer's Manual"
.SH NAME
isatty \- does this descriptor refer to a terminal
.SH SYNOPSIS
.ad l
.nf
.B #include <unistd.h>
.sp
.BI "int isatty(int " desc );
.fi
.ad b
.SH DESCRIPTION
returns 1 if \fIdesc\fP is an open descriptor connected to a terminal and
0 else.
.SH "CONFORMING TO"
SVID, AT&T, X/OPEN, BSD 4.3
.SH "SEE ALSO"
.BR fstat (2),
.BR ttyname (3)
