.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified Mon Apr 12 12:49:57 1993, David Metcalfe
.\" Modified Sat Jul 24 18:56:22 1993, Rik Faith (faith@cs.unc.edu)
.\" Modified Wed Feb 20 21:09:36 2002, Ian Redfern (redferni@logica.com)
.\"
.TH MEMCHR 3  2003-11-01 "" "Linux Programmer's Manual"
.SH NAME
memchr, memrchr \- scan memory for a character
.SH SYNOPSIS
.nf
.B #include <string.h>
.sp
.BI "void *memchr(const void *" s ", int " c ", size_t " n );
.sp
.BI "void *memrchr(const void *" s ", int " c ", size_t " n );
.fi
.SH DESCRIPTION
The 
.B memchr()
function scans the first \fIn\fP bytes of the memory
area pointed to by \fIs\fP for the character \fIc\fP.  The first byte to
match \fIc\fP (interpreted as an unsigned character) stops the operation.
.PP
The 
.B memrchr()
function is like the 
.B memchr()
function,
except that it searches backwards from the end of the \fIn\fP bytes
pointed to by \fIs\fP instead of forwards from the front.
.SH "RETURN VALUE"
The \fBmemchr()\fP and \fBmemrchr()\fP functions return a pointer
to the matching byte or NULL if the character does not occur in
the given memory area.
.SH "CONFORMING TO"
The 
.B memchr() 
function conforms to SVID 3, BSD 4.3, ISO 9899, POSIX.
The 
.B memrchr()
function is a GNU extension, available since glibc 2.1.91.
.SH "SEE ALSO"
.BR index (3),
.BR rindex (3),
.BR strchr (3),
.BR strpbrk (3),
.BR strrchr (3),
.BR strsep (3),
.BR strspn (3),
.BR strstr (3),
.BR wmemchr (3)
