.\" Copyright 2003 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH PUTGRENT 3 2003-09-09 "GNU" "Linux Programmer's Manual"
.SH NAME
putgrent \- write a group database entry to a file
.SH SYNOPSIS
.BR "#define _GNU_SOURCE" "         /* See feature_test_macros(7) */"
.br
.B #include <grp.h>
.sp
.BI "int putgrent(const struct group *" grp ", FILE *" fp );
.SH DESCRIPTION
The
.BR putgrent ()
function is the counterpart for
.BR fgetgrent (3).
The function writes the content of the provided \fIstruct group\fP into the
file pointed to by
.IR fp .
The list of group members must be NULL-terminated or NULL-initialized.
.sp
The \fIstruct group\fP is defined as follows:
.sp
.in +4n
.nf
struct group {
    char   *gr_name;      /* group name */
    char   *gr_passwd;    /* group password */
    gid_t   gr_gid;       /* group ID */
    char  **gr_mem;       /* group members */
};
.fi
.in
.SH RETURN VALUE
The function returns zero on success, and a nonzero value on error.
.SH CONFORMING TO
This function is a GNU extension.
.SH SEE ALSO
.BR fgetgrent (3),
.BR getgrent (3),
.BR group (5)
