.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.TH WCSNCPY 3  2011-09-28 "GNU" "Linux Programmer's Manual"
.SH NAME
wcsncpy \- copy a fixed-size string of wide characters
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcsncpy(wchar_t *" dest ", const wchar_t *" src ", size_t " n );
.fi
.SH DESCRIPTION
The
.BR wcsncpy ()
function is the wide-character equivalent of the
.BR strncpy (3)
function.
It copies at most \fIn\fP wide characters from the wide-character
string pointed to by \fIsrc\fP,
including the terminating null wide character (L\(aq\\0\(aq),
to the array pointed to by \fIdest\fP.
Exactly \fIn\fP wide characters are
written at \fIdest\fP.
If the length \fIwcslen(src)\fP is smaller than \fIn\fP,
the remaining wide characters in the array
pointed to by \fIdest\fP are filled
with null wide characters.
If the length \fIwcslen(src)\fP is greater or equal
to \fIn\fP, the string pointed to by \fIdest\fP
will not be terminated by a null wide character.
.PP
The strings may not overlap.
.PP
The programmer must ensure that there is room for at least \fIn\fP wide
characters at \fIdest\fP.
.SH RETURN VALUE
.BR wcsncpy ()
returns \fIdest\fP.
.SH CONFORMING TO
C99.
.SH SEE ALSO
.BR strncpy (3)
