.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.TH WCSRCHR 3  1999-07-25 "GNU" "Linux Programmer's Manual"
.SH NAME
wcsrchr \- search a wide character in a wide-character string
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcsrchr(const wchar_t *" wcs ", wchar_t " wc );
.fi
.SH DESCRIPTION
The
.BR wcsrchr ()
function is the wide-character equivalent
of the
.BR strrchr (3)
function.
It searches the last occurrence of \fIwc\fP in the wide-character
string pointed to by \fIwcs\fP.
.SH RETURN VALUE
The
.BR wcsrchr ()
function returns a pointer to the last occurrence of
\fIwc\fP in the wide-character string pointed to by \fIwcs\fP, or NULL if
\fIwc\fP does not occur in the string.
.SH CONFORMING TO
C99.
.SH SEE ALSO
.BR strrchr (3),
.BR wcschr (3)
