.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "ERRNO" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" errno 
.SH NAME
errno \- error return value
.SH SYNOPSIS
.LP
\fB#include <errno.h>\fP
.SH DESCRIPTION
.LP
The lvalue \fIerrno\fP is used by many functions to return error values.
.LP
Many functions provide an error number in \fIerrno\fP, which has type
\fBint\fP and is defined in \fI<errno.h>\fP. The value of \fIerrno\fP
shall be defined only after a call to a function
for which it is explicitly stated to be set and until it is changed
by the next function call or if the application assigns it a
value. The value of \fIerrno\fP should only be examined when it is
indicated to be valid by a function's return value.
Applications shall obtain the definition of \fIerrno\fP by the inclusion
of \fI<errno.h>\fP. No function in this volume of IEEE\ Std\ 1003.1-2001
shall set
\fIerrno\fP to 0.
.LP
It is unspecified whether \fIerrno\fP is a macro or an identifier
declared with external linkage. If a macro definition is
suppressed in order to access an actual object, or a program defines
an identifier with the name \fIerrno\fP, the behavior is
undefined.
.LP
The symbolic values stored in \fIerrno\fP are documented in the ERRORS
sections on all relevant pages.
.SH RETURN VALUE
.LP
None.
.SH ERRORS
.LP
None.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
Previously both POSIX and X/Open documents were more restrictive than
the ISO\ C standard in that they required \fIerrno\fP
to be defined as an external variable, whereas the ISO\ C standard
required only that \fIerrno\fP be defined as a modifiable
lvalue with type \fBint\fP.
.LP
An application that needs to examine the value of \fIerrno\fP to determine
the error should set it to 0 before a function call,
then inspect it before a subsequent function call.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIError Numbers\fP , the Base Definitions volume of IEEE\ Std\ 1003.1-2001,
\fI<errno.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
