.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "FEGETENV" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" fegetenv 
.SH NAME
fegetenv, fesetenv \- get and set current floating-point environment
.SH SYNOPSIS
.LP
\fB#include <fenv.h>
.br
.sp
int fegetenv(fenv_t *\fP\fIenvp\fP\fB);
.br
int fesetenv(const fenv_t *\fP\fIenvp\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIfegetenv\fP() function shall attempt to store the current floating-point
environment in the object pointed to by
\fIenvp\fP.
.LP
The \fIfesetenv\fP() function shall attempt to establish the floating-point
environment represented by the object pointed to by
\fIenvp\fP. The argument \fIenvp\fP shall point to an object set by
a call to \fIfegetenv\fP() or \fIfeholdexcept\fP(), or equal a floating-point
environment macro. The \fIfesetenv\fP()
function does not raise floating-point exceptions, but only installs
the state of the floating-point status flags represented
through its argument.
.SH RETURN VALUE
.LP
If the representation was successfully stored, \fIfegetenv\fP() shall
return zero. Otherwise, it shall return a non-zero value.
If the environment was successfully established, \fIfesetenv\fP()
shall return zero. Otherwise, it shall return a non-zero
value.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIfeholdexcept\fP() , \fIfeupdateenv\fP() , the Base
Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<fenv.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
