.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "FGETPOS" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" fgetpos 
.SH NAME
fgetpos \- get current file position information
.SH SYNOPSIS
.LP
\fB#include <stdio.h>
.br
.sp
int fgetpos(FILE *restrict\fP \fIstream\fP\fB, fpos_t *restrict\fP
\fIpos\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIfgetpos\fP() function shall store the current values of the
parse state (if any) and file position indicator for the
stream pointed to by \fIstream\fP in the object pointed to by \fIpos\fP.
The value stored contains unspecified information usable
by \fIfsetpos\fP() for repositioning the stream to its position at
the time of the call to
\fIfgetpos\fP().
.SH RETURN VALUE
.LP
Upon successful completion, \fIfgetpos\fP() shall return 0; otherwise,
it shall return a non-zero value and set \fIerrno\fP to
indicate the error.
.SH ERRORS
.LP
The \fIfgetpos\fP() function shall fail if:
.TP 7
.B EOVERFLOW
The current value of the file position cannot be represented correctly
in an object of type \fBfpos_t\fP. 
.sp
.LP
The \fIfgetpos\fP() function may fail if:
.TP 7
.B EBADF
The file descriptor underlying \fIstream\fP is not valid. 
.TP 7
.B ESPIPE
The file descriptor underlying \fIstream\fP is associated with a pipe,
FIFO, or socket. 
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIfopen\fP() , \fIftell\fP() , \fIrewind\fP() ,
\fIungetc\fP() , the Base Definitions volume of IEEE\ Std\ 1003.1-2001,
\fI<stdio.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
