.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "FTIME" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" ftime 
.SH NAME
ftime \- get date and time (\fBLEGACY\fP)
.SH SYNOPSIS
.LP
\fB#include <sys/timeb.h>
.br
.sp
int ftime(struct timeb *\fP\fItp\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The \fIftime\fP() function shall set the \fItime\fP and \fImillitm\fP
members of the \fBtimeb\fP structure pointed to by
\fItp\fP to contain the seconds and milliseconds portions, respectively,
of the current time in seconds since the Epoch. The
contents of the \fItimezone\fP and \fIdstflag\fP members of \fItp\fP
after a call to \fIftime\fP() are unspecified.
.LP
The system clock need not have millisecond granularity. Depending
on any granularity (particularly a granularity of one) renders
code non-portable.
.SH RETURN VALUE
.LP
Upon successful completion, the \fIftime\fP() function shall return
0; otherwise, -1 shall be returned.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.SS Getting the Current Time and Date
.LP
The following example shows how to get the current system time values
using the \fIftime\fP() function. The \fBtimeb\fP
structure pointed to by \fItp\fP is filled with the current system
time values for \fItime\fP and \fImillitm\fP.
.sp
.RS
.nf

\fB#include <sys/timeb.h>
.sp

struct timeb tp;
int          status;
\&...
status = ftime(&tp);
\fP
.fi
.RE
.SH APPLICATION USAGE
.LP
For applications portability, the \fItime\fP() function should be
used to determine the
current time instead of \fIftime\fP(). Realtime applications should
use \fIclock_gettime\fP() to determine the current time instead of
\fIftime\fP().
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
This function may be withdrawn in a future version.
.SH SEE ALSO
.LP
\fIclock_getres\fP() , \fIctime\fP() , \fIgettimeofday\fP() , \fItime\fP()
, the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<sys/timeb.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
