.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "GAI_STRERROR" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" gai_strerror 
.SH NAME
gai_strerror \- address and name information error description
.SH SYNOPSIS
.LP
\fB#include <netdb.h>
.br
.sp
const char *gai_strerror(int\fP \fIecode\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIgai_strerror\fP() function shall return a text string describing
an error value for the \fIgetaddrinfo\fP() and \fIgetnameinfo\fP()
functions listed in the \fI<netdb.h>\fP header.
.LP
When the \fIecode\fP argument is one of the following values listed
in the \fI<netdb.h>\fP header:
.sp
.RS
.nf

[EAI_AGAIN]
[EAI_BADFLAGS]
[EAI_FAIL]
[EAI_FAMILY]
[EAI_MEMORY]
[EAI_NONAME]
[EAI_OVERFLOW]
[EAI_SERVICE]
[EAI_SOCKTYPE]
[EAI_SYSTEM]
.fi
.RE
.LP
the function return value shall point to a string describing the error.
If the argument is not one of those values, the function
shall return a pointer to a string whose contents indicate an unknown
error.
.SH RETURN VALUE
.LP
Upon successful completion, \fIgai_strerror\fP() shall return a pointer
to an implementation-defined string.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIgetaddrinfo\fP() , the Base Definitions volume of IEEE\ Std\ 1003.1-2001,
\fI<netdb.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
