.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "GETHOSTNAME" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" gethostname 
.SH NAME
gethostname \- get name of current host
.SH SYNOPSIS
.LP
\fB#include <unistd.h>
.br
.sp
int gethostname(char *\fP\fIname\fP\fB, size_t\fP \fInamelen\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIgethostname\fP() function shall return the standard host name
for the current machine. The \fInamelen\fP argument shall
specify the size of the array pointed to by the \fIname\fP argument.
The returned name shall be null-terminated, except that if
\fInamelen\fP is an insufficient length to hold the host name, then
the returned name shall be truncated and it is unspecified
whether the returned name is null-terminated.
.LP
Host names are limited to {HOST_NAME_MAX} bytes.
.SH RETURN VALUE
.LP
Upon successful completion, 0 shall be returned; otherwise, -1 shall
be returned.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIgethostid\fP() , \fIuname\fP() , the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<unistd.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
