.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "GETPGID" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" getpgid 
.SH NAME
getpgid \- get the process group ID for a process
.SH SYNOPSIS
.LP
\fB#include <unistd.h>
.br
.sp
pid_t getpgid(pid_t\fP \fIpid\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The \fIgetpgid\fP() function shall return the process group ID of
the process whose process ID is equal to \fIpid\fP. If
\fIpid\fP is equal to 0, \fIgetpgid\fP() shall return the process
group ID of the calling process.
.SH RETURN VALUE
.LP
Upon successful completion, \fIgetpgid\fP() shall return a process
group ID. Otherwise, it shall return (\fBpid_t\fP)-1 and
set \fIerrno\fP to indicate the error.
.SH ERRORS
.LP
The \fIgetpgid\fP() function shall fail if:
.TP 7
.B EPERM
The process whose process ID is equal to \fIpid\fP is not in the same
session as the calling process, and the implementation
does not allow access to the process group ID of that process from
the calling process.
.TP 7
.B ESRCH
There is no process with a process ID equal to \fIpid\fP.
.sp
.LP
The \fIgetpgid\fP() function may fail if:
.TP 7
.B EINVAL
The value of the \fIpid\fP argument is invalid.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIexec\fP() , \fIfork\fP() , \fIgetpgrp\fP() , \fIgetpid\fP() , \fIgetsid\fP()
, \fIsetpgid\fP() , \fIsetsid\fP() , the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<unistd.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
