.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "GETS" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" gets 
.SH NAME
gets \- get a string from a stdin stream
.SH SYNOPSIS
.LP
\fB#include <stdio.h>
.br
.sp
char *gets(char *\fP\fIs\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIgets\fP() function shall read bytes from the standard input
stream, \fIstdin\fP, into the array pointed to by \fIs\fP,
until a <newline> is read or an end-of-file condition is encountered.
Any <newline> shall be discarded and a null byte
shall be placed immediately after the last byte read into the array.
.LP
The
\fIgets\fP() function may mark the \fIst_atime\fP field of the file
associated with \fIstream\fP for update. The \fIst_atime\fP
field shall be marked for update by the first successful execution
of \fIfgetc\fP(), \fIfgets\fP(), \fIfread\fP(), \fIgetc\fP(), \fIgetchar\fP(),
\fIgets\fP(), \fIfscanf\fP(), or \fIscanf\fP() using \fIstream\fP
that
returns data not supplied by a prior call to \fIungetc\fP(). 
.SH RETURN VALUE
.LP
Upon successful completion, \fIgets\fP() shall return \fIs\fP. If
the stream is at end-of-file, the end-of-file indicator for
the stream shall be set and \fIgets\fP() shall return a null pointer.
If a read error occurs, the error indicator for the stream
shall be set, \fIgets\fP() shall return a null pointer,   \ and set
\fIerrno\fP to indicate the error. 
.SH ERRORS
.LP
Refer to \fIfgetc\fP() .
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
Reading a line that overflows the array pointed to by \fIs\fP results
in undefined behavior. The use of \fIfgets\fP() is recommended.
.LP
Since the user cannot specify the length of the buffer passed to \fIgets\fP(),
use of this function is discouraged. The length
of the string read is unlimited. It is possible to overflow this buffer
in such a way as to cause applications to fail, or possible
system security violations.
.LP
It is recommended that the \fIfgets\fP() function should be used to
read input lines.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIfeof\fP() , \fIferror\fP() , \fIfgets\fP() ,
the Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<stdio.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
