.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "ISLESS" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" isless 
.SH NAME
isless \- test if x is less than y
.SH SYNOPSIS
.LP
\fB#include <math.h>
.br
.sp
int isless(real-floating\fP \fIx\fP\fB, real-floating\fP \fIy\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIisless\fP() macro shall determine whether its first argument
is less than its second argument. The value of
\fIisless\fP( \fIx\fP, \fIy\fP) shall be equal to (\fIx\fP)\ <\ (\fIy\fP);
however, unlike
(\fIx\fP)\ <\ (\fIy\fP), \fIisless\fP( \fIx\fP, \fIy\fP) shall not
raise the invalid floating-point exception when
\fIx\fP and \fIy\fP are unordered.
.SH RETURN VALUE
.LP
Upon successful completion, the \fIisless\fP() macro shall return
the value of (\fIx\fP)\ <\ (\fIy\fP).
.LP
If \fIx\fP or \fIy\fP is NaN, 0 shall be returned.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
The relational and equality operators support the usual mathematical
relationships between numeric values. For any ordered pair
of numeric values, exactly one of the relationships (less, greater,
and equal) is true. Relational operators may raise the invalid
floating-point exception when argument values are NaNs. For a NaN
and a numeric value, or for two NaNs, just the unordered
relationship is true. This macro is a quiet (non-floating-point exception
raising) version of a relational operator. It facilitates
writing efficient code that accounts for NaNs without suffering the
invalid floating-point exception. In the SYNOPSIS section,
\fBreal-floating\fP indicates that the argument shall be an expression
of \fBreal-floating\fP type.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIisgreater\fP() , \fIisgreaterequal\fP() , \fIislessequal\fP() ,
\fIislessgreater\fP() , \fIisunordered\fP() , the Base Definitions
volume of IEEE\ Std\ 1003.1-2001, \fI<math.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
