.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "MALLOC" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" malloc 
.SH NAME
malloc \- a memory allocator
.SH SYNOPSIS
.LP
\fB#include <stdlib.h>
.br
.sp
void *malloc(size_t\fP \fIsize\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fImalloc\fP() function shall allocate unused space for an object
whose size in bytes is specified by \fIsize\fP and whose
value is unspecified.
.LP
The order and contiguity of storage allocated by successive calls
to \fImalloc\fP() is unspecified. The pointer returned if the
allocation succeeds shall be suitably aligned so that it may be assigned
to a pointer to any type of object and then used to access
such an object in the space allocated (until the space is explicitly
freed or reallocated). Each such allocation shall yield a
pointer to an object disjoint from any other object. The pointer returned
points to the start (lowest byte address) of the
allocated space. If the space cannot be allocated, a null pointer
shall be returned. If the size of the space requested is 0, the
behavior is implementation-defined: the value returned shall be either
a null pointer or a unique pointer.
.SH RETURN VALUE
.LP
Upon successful completion with \fIsize\fP not equal to 0, \fImalloc\fP()
shall return a pointer to the allocated space. If
\fIsize\fP is 0, either a null pointer or a unique pointer that can
be successfully passed to \fIfree\fP() shall be returned. Otherwise,
it shall return a null pointer   \ and set
\fIerrno\fP to indicate the error. 
.SH ERRORS
.LP
The \fImalloc\fP() function shall fail if:
.TP 7
.B ENOMEM
Insufficient storage space is available. 
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIcalloc\fP() , \fIfree\fP() , \fIrealloc\fP()
, the Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<stdlib.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
