.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "MBSINIT" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" mbsinit 
.SH NAME
mbsinit \- determine conversion object status
.SH SYNOPSIS
.LP
\fB#include <wchar.h>
.br
.sp
int mbsinit(const mbstate_t *\fP\fIps\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
If \fIps\fP is not a null pointer, the \fImbsinit\fP() function shall
determine whether the object pointed to by \fIps\fP
describes an initial conversion state.
.SH RETURN VALUE
.LP
The \fImbsinit\fP() function shall return non-zero if \fIps\fP is
a null pointer, or if the pointed-to object describes an
initial conversion state; otherwise, it shall return zero.
.LP
If an \fBmbstate_t\fP object is altered by any of the functions described
as "restartable", and is then used with a different
character sequence, or in the other conversion direction, or with
a different \fILC_CTYPE\fP category setting than on earlier
function calls, the behavior is undefined.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
The \fBmbstate_t\fP object is used to describe the current conversion
state from a particular character sequence to a
wide-character sequence (or \fIvice versa\fP) under the rules of a
particular setting of the \fILC_CTYPE\fP category of the
current locale.
.LP
The initial conversion state corresponds, for a conversion in either
direction, to the beginning of a new character sequence in
the initial shift state. A zero valued \fBmbstate_t\fP object is at
least one way to describe an initial conversion state. A zero
valued \fBmbstate_t\fP object can be used to initiate conversion involving
any character sequence, in any \fILC_CTYPE\fP category
setting.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fImbrlen\fP() , \fImbrtowc\fP() , \fIwcrtomb\fP() , \fImbsrtowcs\fP()
, \fIwcsrtombs\fP() , the Base Definitions volume of IEEE\ Std\ 1003.1-2001,
\fI<wchar.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
