.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "MBSTOWCS" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" mbstowcs 
.SH NAME
mbstowcs \- convert a character string to a wide-character string
.SH SYNOPSIS
.LP
\fB#include <stdlib.h>
.br
.sp
size_t mbstowcs(wchar_t *restrict\fP \fIpwcs\fP\fB, const char *restrict\fP
\fIs\fP\fB,
.br
\ \ \ \ \ \  size_t\fP \fIn\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fImbstowcs\fP() function shall convert a sequence of characters
that begins in the initial shift state from the array
pointed to by \fIs\fP into a sequence of corresponding wide-character
codes and shall store not more than \fIn\fP wide-character
codes into the array pointed to by \fIpwcs\fP. No characters that
follow a null byte (which is converted into a wide-character
code with value 0) shall be examined or converted. Each character
shall be converted as if by a call to \fImbtowc\fP(), except that
the shift state of \fImbtowc\fP() is not affected.
.LP
No more than \fIn\fP elements shall be modified in the array pointed
to by \fIpwcs\fP. If copying takes place between objects
that overlap, the behavior is undefined.
.LP
The behavior of this function shall be affected by the \fILC_CTYPE\fP
category of the current locale.   \ If
\fIpwcs\fP is a null pointer, \fImbstowcs\fP() shall return the length
required to convert the entire array regardless of the
value of \fIn\fP, but no values are stored. 
.SH RETURN VALUE
.LP
If an invalid character is encountered, \fImbstowcs\fP() shall return
(\fBsize_t\fP)-1   \ and may set
\fIerrno\fP to indicate the error. 
.LP
Otherwise, \fImbstowcs\fP() shall return the number of the array elements
modified   \ (or required
if \fIpwcs\fP is null),  not including a terminating 0 code, if
any. The array shall not be zero-terminated if the value returned
is \fIn\fP.
.SH ERRORS
.LP
The \fImbstowcs\fP() function may fail if:
.TP 7
.B EILSEQ
Invalid byte sequence is detected. 
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fImblen\fP() , \fImbtowc\fP() , \fIwctomb\fP()
, \fIwcstombs\fP() , the Base Definitions volume of IEEE\ Std\ 1003.1-2001,
\fI<stdlib.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
