.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "MEMMOVE" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" memmove 
.SH NAME
memmove \- copy bytes in memory with overlapping areas
.SH SYNOPSIS
.LP
\fB#include <string.h>
.br
.sp
void *memmove(void *\fP\fIs1\fP\fB, const void *\fP\fIs2\fP\fB, size_t\fP
\fIn\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fImemmove\fP() function shall copy \fIn\fP bytes from the object
pointed to by \fIs2\fP into the object pointed to by
\fIs1\fP. Copying takes place as if the \fIn\fP bytes from the object
pointed to by \fIs2\fP are first copied into a temporary
array of \fIn\fP bytes that does not overlap the objects pointed to
by \fIs1\fP and \fIs2\fP, and then the \fIn\fP bytes from
the temporary array are copied into the object pointed to by \fIs1\fP.
.SH RETURN VALUE
.LP
The \fImemmove\fP() function shall return \fIs1\fP; no return value
is reserved to indicate an error.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
The Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<string.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
