.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "MODF" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" modf 
.SH NAME
modf, modff, modfl \- decompose a floating-point number
.SH SYNOPSIS
.LP
\fB#include <math.h>
.br
.sp
double modf(double\fP \fIx\fP\fB, double *\fP\fIiptr\fP\fB);
.br
float modff(float\fP \fIvalue\fP\fB, float *\fP\fIiptr\fP\fB);
.br
long double modfl(long double\fP \fIvalue\fP\fB, long double *\fP\fIiptr\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
These functions shall break the argument \fIx\fP into integral and
fractional parts, each of which has the same sign as the
argument. It stores the integral part as a \fBdouble\fP (for the \fImodf\fP()
function), a \fBfloat\fP (for the \fImodff\fP()
function), or a \fBlong double\fP (for the \fImodfl\fP() function),
in the object pointed to by \fIiptr\fP.
.SH RETURN VALUE
.LP
Upon successful completion, these functions shall return the signed
fractional part of \fIx\fP.
.LP
If
\fIx\fP is NaN, a NaN shall be returned, and *\fIiptr\fP shall be
set to a NaN.
.LP
If \fIx\fP is \(+-Inf, \(+-0 shall be returned, and *\fIiptr\fP shall
be set to \(+-Inf. 
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
The \fImodf\fP() function computes the function result and *\fIiptr\fP
such that:
.sp
.RS
.nf

\fBa = modf(x, iptr) ;
x == a+*iptr ;
\fP
.fi
.RE
.LP
allowing for the usual floating-point inaccuracies.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIfrexp\fP() , \fIisnan\fP() , \fIldexp\fP() ,
the Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<math.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
