.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "POSIX_TRACE_EVENTTYPELIST_GETNEXT_ID" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" posix_trace_eventtypelist_getnext_id 
.SH NAME
posix_trace_eventtypelist_getnext_id, posix_trace_eventtypelist_rewind
\- iterate over a mapping of trace event types
(\fBTRACING\fP)
.SH SYNOPSIS
.LP
\fB#include <trace.h>
.br
.sp
int posix_trace_eventtypelist_getnext_id(trace_id_t\fP \fItrid\fP\fB,
.br
\ \ \ \ \ \  trace_event_id_t *restrict\fP \fIevent\fP\fB, int *restrict\fP
\fIunavailable\fP\fB);
.br
int posix_trace_eventtypelist_rewind(trace_id_t\fP \fItrid\fP\fB);
\fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The first time \fIposix_trace_eventtypelist_getnext_id\fP() is called,
the function shall return in the variable pointed to by
\fIevent\fP the first trace event type identifier of the list of trace
events of the trace stream identified by the \fItrid\fP
argument. Successive calls to \fIposix_trace_eventtypelist_getnext_id\fP()
return in the variable pointed to by \fIevent\fP the
next trace event type identifier in that same list. Each time a trace
event type identifier is successfully written into the
variable pointed to by the \fIevent\fP argument, the variable pointed
to by the \fIunavailable\fP argument shall be set to zero.
When no more trace event type identifiers are available, and so none
is returned, the variable pointed to by the \fIunavailable\fP
argument shall be set to a value different from zero.
.LP
The \fIposix_trace_eventtypelist_rewind\fP() function shall reset
the next trace event type identifier to be read to the first
trace event type identifier from the list of trace events used in
the trace stream identified by \fItrid\fP.
.SH RETURN VALUE
.LP
Upon successful completion, these functions shall return a value of
zero. Otherwise, they shall return the corresponding error
number.
.LP
The \fIposix_trace_eventtypelist_getnext_id\fP() function stores the
trace event type identifier value in the object pointed to
by \fIevent\fP, if successful.
.SH ERRORS
.LP
These functions shall fail if:
.TP 7
.B EINVAL
The \fItrid\fP argument was not a valid trace stream identifier.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIposix_trace_event\fP() , \fIposix_trace_getnext_event\fP() , \fIposix_trace_trid_eventid_open\fP()
, the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<trace.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
