.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "POSIX_SPAWNATTR_GETFLAGS" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" posix_spawnattr_getflags 
.SH NAME
posix_spawnattr_getflags, posix_spawnattr_setflags \- get and set the
spawn\-flags attribute of a spawn attributes object
(\fBADVANCED REALTIME\fP)
.SH SYNOPSIS
.LP
\fB#include <spawn.h>
.br
.sp
int posix_spawnattr_getflags(const posix_spawnattr_t *restrict\fP
\fIattr\fP\fB,
.br
\ \ \ \ \ \  short *restrict\fP \fIflags\fP\fB);
.br
int posix_spawnattr_setflags(posix_spawnattr_t *\fP\fIattr\fP\fB,
short\fP \fIflags\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The \fIposix_spawnattr_getflags\fP() function shall obtain the value
of the \fIspawn-flags\fP attribute from the attributes
object referenced by \fIattr\fP.
.LP
The \fIposix_spawnattr_setflags\fP() function shall set the \fIspawn-flags\fP
attribute in an initialized attributes object
referenced by \fIattr\fP.
.LP
The \fIspawn-flags\fP attribute is used to indicate which process
attributes are to be changed in the new process image when
invoking \fIposix_spawn\fP() or \fIposix_spawnp\fP(). It is the bitwise-inclusive
OR of zero or more of the following
flags:
.LP
.sp
POSIX_SPAWN_RESETIDS
.br
POSIX_SPAWN_SETPGROUP
.br
POSIX_SPAWN_SETSIGDEF
.br
POSIX_SPAWN_SETSIGMASK
.br
.sp
POSIX_SPAWN_SETSCHEDPARAM
.br
POSIX_SPAWN_SETSCHEDULER
.br
.sp
.LP
These flags are defined in \fI<spawn.h>\fP. The default value of this
attribute
shall be as if no flags were set.
.SH RETURN VALUE
.LP
Upon successful completion, \fIposix_spawnattr_getflags\fP() shall
return zero and store the value of the \fIspawn-flags\fP
attribute of \fIattr\fP into the object referenced by the \fIflags\fP
parameter; otherwise, an error number shall be returned to
indicate the error.
.LP
Upon successful completion, \fIposix_spawnattr_setflags\fP() shall
return zero; otherwise, an error number shall be returned to
indicate the error.
.SH ERRORS
.LP
These functions may fail if:
.TP 7
.B EINVAL
The value specified by \fIattr\fP is invalid.
.sp
.LP
The \fIposix_spawnattr_setflags\fP() function may fail if:
.TP 7
.B EINVAL
The value of the attribute being set is not valid.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
These functions are part of the Spawn option and need not be provided
on all implementations.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIposix_spawn\fP() , \fIposix_spawnattr_destroy\fP() , \fIposix_spawnattr_init\fP()
, \fIposix_spawnattr_getsigdefault\fP() , \fIposix_spawnattr_getpgroup\fP()
, \fIposix_spawnattr_getschedparam\fP() , \fIposix_spawnattr_getschedpolicy\fP()
, \fIposix_spawnattr_getsigmask\fP() , \fIposix_spawnattr_setsigdefault\fP()
, \fIposix_spawnattr_setpgroup\fP() , \fIposix_spawnattr_setschedparam\fP()
, \fIposix_spawnattr_setschedpolicy\fP() , \fIposix_spawnattr_setsigmask\fP()
, \fIposix_spawnp\fP() ,
the Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<spawn.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
