.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "POSIX_TRACE_START" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" posix_trace_start 
.SH NAME
posix_trace_start, posix_trace_stop \- trace start and stop (\fBTRACING\fP)
.SH SYNOPSIS
.LP
\fB#include <trace.h>
.br
.sp
int posix_trace_start(trace_id_t\fP \fItrid\fP\fB);
.br
int posix_trace_stop (trace_id_t\fP \fItrid\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The \fIposix_trace_start\fP() and \fIposix_trace_stop\fP() functions,
respectively, shall start and stop the trace stream
identified by the argument \fItrid\fP.
.LP
The effect of calling the \fIposix_trace_start\fP() function shall
be recorded in the trace stream as the POSIX_TRACE_START
system trace event and the status of the trace stream shall become
POSIX_TRACE_RUNNING. If the trace stream is in progress when
this function is called, the POSIX_TRACE_START system trace event
shall not be recorded and the trace stream shall continue to run.
If the trace stream is full, the POSIX_TRACE_START system trace event
shall not be recorded and the status of the trace stream
shall not be changed.
.LP
The effect of calling the \fIposix_trace_stop\fP() function shall
be recorded in the trace stream as the POSIX_TRACE_STOP
system trace event and the status of the trace stream shall become
POSIX_TRACE_SUSPENDED. If the trace stream is suspended when
this function is called, the POSIX_TRACE_STOP system trace event shall
not be recorded and the trace stream shall remain suspended.
If the trace stream is full, the POSIX_TRACE_STOP system trace event
shall not be recorded and the status of the trace stream shall
not be changed.
.SH RETURN VALUE
.LP
Upon successful completion, these functions shall return a value of
zero. Otherwise, they shall return the corresponding error
number.
.SH ERRORS
.LP
These functions shall fail if:
.TP 7
.B EINVAL
The value of the argument \fItrid\fP does not correspond to an active
trace stream and thus no trace stream was started or
stopped.
.TP 7
.B EINTR
The operation was interrupted by a signal and thus the trace stream
was not necessarily started or stopped.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIposix_trace_create\fP() , the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<trace.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
