.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "PTHREAD_ATTR_GETINHERITSCHED" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" pthread_attr_getinheritsched 
.SH NAME
pthread_attr_getinheritsched, pthread_attr_setinheritsched \- get and
set the inheritsched attribute (\fBREALTIME
THREADS\fP)
.SH SYNOPSIS
.LP
\fB#include <pthread.h>
.br
.sp
int pthread_attr_getinheritsched(const pthread_attr_t *restrict\fP
\fIattr\fP\fB,
.br
\ \ \ \ \ \  int *restrict\fP \fIinheritsched\fP\fB);
.br
int pthread_attr_setinheritsched(pthread_attr_t *\fP\fIattr\fP\fB,
.br
\ \ \ \ \ \  int\fP \fIinheritsched\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The \fIpthread_attr_getinheritsched\fP(), and \fIpthread_attr_setinheritsched\fP()
functions, respectively, shall get and set
the \fIinheritsched\fP attribute in the \fIattr\fP argument.
.LP
When the attributes objects are used by \fIpthread_create\fP(), the
\fIinheritsched\fP attribute determines how the other scheduling attributes
of the created thread shall be set.
.TP 7
PTHREAD_INHERIT_SCHED
.sp
Specifies that the thread scheduling attributes shall be inherited
from the creating thread, and the scheduling attributes in this
\fIattr\fP argument shall be ignored.
.TP 7
PTHREAD_EXPLICIT_SCHED
.sp
Specifies that the thread scheduling attributes shall be set to the
corresponding values from this attributes object.
.sp
.LP
The symbols PTHREAD_INHERIT_SCHED and PTHREAD_EXPLICIT_SCHED are defined
in the \fI<pthread.h>\fP header.
.LP
The following thread scheduling attributes defined by IEEE\ Std\ 1003.1-2001
are affected by the \fIinheritsched\fP
attribute: scheduling policy ( \fIschedpolicy\fP), scheduling parameters
( \fIschedparam\fP), and scheduling contention scope (
\fIcontentionscope\fP).
.SH RETURN VALUE
.LP
If successful, the \fIpthread_attr_getinheritsched\fP() and \fIpthread_attr_setinheritsched\fP()
functions shall return zero;
otherwise, an error number shall be returned to indicate the error.
.SH ERRORS
.LP
The \fIpthread_attr_setinheritsched\fP() function may fail if:
.TP 7
.B EINVAL
The value of \fIinheritsched\fP is not valid.
.TP 7
.B ENOTSUP
An attempt was made to set the attribute to an unsupported value.
.sp
.LP
These functions shall not return an error code of [EINTR].
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
After these attributes have been set, a thread can be created with
the specified attributes using \fIpthread_create\fP(). Using these
routines does not affect the current running
thread.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIpthread_attr_destroy\fP() , \fIpthread_attr_getscope\fP() , \fIpthread_attr_getschedpolicy\fP()
, \fIpthread_attr_getschedparam\fP() , \fIpthread_create\fP() , the
Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<pthread.h>\fP,
\fI<sched.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
