.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "PTHREAD_ATTR_GETSTACKSIZE" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" pthread_attr_getstacksize 
.SH NAME
pthread_attr_getstacksize, pthread_attr_setstacksize \- get and set
the stacksize attribute
.SH SYNOPSIS
.LP
\fB#include <pthread.h>
.br
.sp
int pthread_attr_getstacksize(const pthread_attr_t *restrict\fP \fIattr\fP\fB,
.br
\ \ \ \ \ \  size_t *restrict\fP \fIstacksize\fP\fB);
.br
int pthread_attr_setstacksize(pthread_attr_t *\fP\fIattr\fP\fB, size_t\fP
\fIstacksize\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The \fIpthread_attr_getstacksize\fP() and \fIpthread_attr_setstacksize\fP()
functions, respectively, shall get and set the
thread creation \fIstacksize\fP attribute in the \fIattr\fP object.
.LP
The \fIstacksize\fP attribute shall define the minimum stack size
(in bytes) allocated for the created threads stack.
.SH RETURN VALUE
.LP
Upon successful completion, \fIpthread_attr_getstacksize\fP() and
\fIpthread_attr_setstacksize\fP() shall return a value of 0;
otherwise, an error number shall be returned to indicate the error.
.LP
The \fIpthread_attr_getstacksize\fP() function stores the \fIstacksize\fP
attribute value in \fIstacksize\fP if
successful.
.SH ERRORS
.LP
The \fIpthread_attr_setstacksize\fP() function shall fail if:
.TP 7
.B EINVAL
The value of \fIstacksize\fP is less than {PTHREAD_STACK_MIN} or exceeds
a system-imposed limit.
.sp
.LP
These functions shall not return an error code of [EINTR].
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIpthread_attr_destroy\fP() , \fIpthread_attr_getstackaddr\fP() ,
\fIpthread_attr_getdetachstate\fP() , \fIpthread_create\fP() , the
Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<limits.h>\fP,
\fI<pthread.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
