.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "REMOVE" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" remove 
.SH NAME
remove \- remove a file
.SH SYNOPSIS
.LP
\fB#include <stdio.h>
.br
.sp
int remove(const char *\fP\fIpath\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIremove\fP() function shall cause the file named by the pathname
pointed to by \fIpath\fP to be no longer accessible by
that name. A subsequent attempt to open that file using that name
shall fail, unless it is created anew.
.LP
If
\fIpath\fP does not name a directory, \fIremove\fP(\fIpath\fP) shall
be equivalent to \fIunlink\fP(\fIpath\fP).
.LP
If \fIpath\fP names a directory, \fIremove\fP(\fIpath\fP) shall be
equivalent to \fIrmdir\fP(\fIpath\fP). 
.SH RETURN VALUE
.LP
Refer to \fIrmdir\fP() or \fIunlink\fP() . 
.SH ERRORS
.LP
Refer to \fIrmdir\fP() or \fIunlink\fP() . 
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.SS Removing Access to a File
.LP
The following example shows how to remove access to a file named \fB/home/cnd/old_mods\fP.
.sp
.RS
.nf

\fB#include <stdio.h>
.sp

int status;
\&...
status = remove("/home/cnd/old_mods");
\fP
.fi
.RE
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIrmdir\fP() , \fIunlink\fP() , the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<stdio.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
