.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "RINT" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" rint 
.SH NAME
rint, rintf, rintl \- round-to-nearest integral value
.SH SYNOPSIS
.LP
\fB#include <math.h>
.br
.sp
double rint(double\fP \fIx\fP\fB);
.br
float rintf(float\fP \fIx\fP\fB);
.br
long double rintl(long double\fP \fIx\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
These functions shall return the integral value (represented as a
\fBdouble\fP) nearest \fIx\fP in the direction of the
current rounding mode. The current rounding mode is implementation-defined.
.LP
If the current rounding mode rounds toward negative infinity, then
\fIrint\fP() shall be equivalent to \fIfloor\fP() . If the current
rounding mode rounds toward positive infinity, then \fIrint\fP() shall
be
equivalent to \fIceil\fP() .
.LP
These functions differ from the \fInearbyint\fP(), \fInearbyintf\fP(),
and \fInearbyintl\fP()
functions only in that they may raise the inexact floating-point exception
if the result differs in value from the argument.
.LP
An application wishing to check for error situations should set \fIerrno\fP
to zero and call
\fIfeclearexcept\fP(FE_ALL_EXCEPT) before calling these functions.
On return, if \fIerrno\fP is non-zero or
\fIfetestexcept\fP(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW)
is non-zero, an error has occurred.
.SH RETURN VALUE
.LP
Upon successful completion, these functions shall return the integer
(represented as a double precision number) nearest \fIx\fP
in the direction of the current rounding mode.
.LP
If
\fIx\fP is NaN, a NaN shall be returned.
.LP
If \fIx\fP is \(+-0 or \(+-Inf, \fIx\fP shall be returned. 
.LP
If the correct value would cause overflow, a range error shall occur
and \fIrint\fP(), \fIrintf\fP(), and \fIrintl\fP() shall
return the value of the macro \(+-HUGE_VAL, \(+-HUGE_VALF, and \(+-HUGE_VALL
(with the same sign as \fIx\fP),
respectively. 
.SH ERRORS
.LP
These functions shall fail if:
.TP 7
Range\ Error
The result would cause an overflow. 
.LP
If the integer expression (math_errhandling & MATH_ERRNO) is non-zero,
then \fIerrno\fP shall be set to [ERANGE]. If the
integer expression (math_errhandling & MATH_ERREXCEPT) is non-zero,
then the overflow floating-point exception shall be raised.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
On error, the expressions (math_errhandling & MATH_ERRNO) and (math_errhandling
& MATH_ERREXCEPT) are independent of
each other, but at least one of them must be non-zero.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIabs\fP() , \fIceil\fP() , \fIfeclearexcept\fP() , \fIfetestexcept\fP()
, \fIfloor\fP() , \fIisnan\fP() , \fInearbyint\fP() , the
Base Definitions volume of IEEE\ Std\ 1003.1-2001, Section 4.18, Treatment
of Error Conditions for Mathematical Functions, \fI<math.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
