.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "SETEUID" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" seteuid 
.SH NAME
seteuid \- set effective user ID
.SH SYNOPSIS
.LP
\fB#include <unistd.h>
.br
.sp
int seteuid(uid_t\fP \fIuid\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
If \fIuid\fP is equal to the real user ID or the saved set-user-ID,
or if the process has appropriate privileges,
\fIseteuid\fP() shall set the effective user ID of the calling process
to \fIuid\fP; the real user ID and saved set-user-ID shall
remain unchanged.
.LP
The \fIseteuid\fP() function shall not affect the supplementary group
list in any way.
.SH RETURN VALUE
.LP
Upon successful completion, 0 shall be returned; otherwise, -1 shall
be returned and \fIerrno\fP set to indicate the error.
.SH ERRORS
.LP
The \fIseteuid\fP() function shall fail if:
.TP 7
.B EINVAL
The value of the \fIuid\fP argument is invalid and is not supported
by the implementation.
.TP 7
.B EPERM
The process does not have appropriate privileges and \fIuid\fP does
not match the real group ID or the saved
set-group-ID.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
Refer to the RATIONALE section in \fIsetuid\fP() .
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIexec\fP() , \fIgetegid\fP() , \fIgeteuid\fP() , \fIgetgid\fP()
, \fIgetuid\fP() ,
\fIsetegid\fP() , \fIsetgid\fP() , \fIsetregid\fP() , \fIsetreuid\fP()
, \fIsetuid\fP() ,
the Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<sys/types.h>\fP,
\fI<unistd.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
