.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "SIGDELSET" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" sigdelset 
.SH NAME
sigdelset \- delete a signal from a signal set
.SH SYNOPSIS
.LP
\fB#include <signal.h>
.br
.sp
int sigdelset(sigset_t *\fP\fIset\fP\fB, int\fP \fIsigno\fP\fB); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The \fIsigdelset\fP() function deletes the individual signal specified
by \fIsigno\fP from the signal set pointed to by
\fIset\fP.
.LP
Applications should call either \fIsigemptyset\fP() or \fIsigfillset\fP()
at least once for each object of type \fBsigset_t\fP prior to any
other use
of that object. If such an object is not initialized in this way,
but is nonetheless supplied as an argument to any of \fIpthread_sigmask\fP(),
\fIsigaction\fP(), \fIsigaddset\fP(), \fIsigdelset\fP(), \fIsigismember\fP(),
\fIsigpending\fP(), \fIsigprocmask\fP(), \fIsigsuspend\fP(), \fIsigtimedwait\fP(),
\fIsigwait\fP(), or \fIsigwaitinfo\fP(), the results are undefined.
.SH RETURN VALUE
.LP
Upon successful completion, \fIsigdelset\fP() shall return 0; otherwise,
it shall return -1 and set \fIerrno\fP to indicate
the error.
.SH ERRORS
.LP
The \fIsigdelset\fP() function may fail if:
.TP 7
.B EINVAL
The \fIsigno\fP argument is not a valid signal number, or is an unsupported
signal number.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fISignal Concepts\fP , \fIsigaction\fP() , \fIsigaddset\fP() , \fIsigemptyset\fP()
, \fIsigfillset\fP() , \fIsigismember\fP() , \fIsigpending\fP() ,
\fIsigprocmask\fP() , \fIsigsuspend\fP() , the Base Definitions volume
of IEEE\ Std\ 1003.1-2001, \fI<signal.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
