.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "STRLEN" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" strlen 
.SH NAME
strlen \- get string length
.SH SYNOPSIS
.LP
\fB#include <string.h>
.br
.sp
size_t strlen(const char *\fP\fIs\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIstrlen\fP() function shall compute the number of bytes in the
string to which \fIs\fP points, not including the
terminating null byte.
.SH RETURN VALUE
.LP
The \fIstrlen\fP() function shall return the length of \fIs\fP; no
return value shall be reserved to indicate an error.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.SS Getting String Lengths
.LP
The following example sets the maximum length of \fIkey\fP and \fIdata\fP
by using \fIstrlen\fP() to get the lengths of those
strings.
.sp
.RS
.nf

\fB#include <string.h>
\&...
struct element {
    char *key;
    char *data;
};
\&...
char *key, *data;
int len;
.sp

*keylength = *datalength = 0;
\&...
if ((len = strlen(key)) > *keylength)
    *keylength = len;
if ((len = strlen(data)) > *datalength)
    *datalength = len;
\&...
\fP
.fi
.RE
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
The Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<string.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
