.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "TCGETPGRP" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" tcgetpgrp 
.SH NAME
tcgetpgrp \- get the foreground process group ID
.SH SYNOPSIS
.LP
\fB#include <unistd.h>
.br
.sp
pid_t tcgetpgrp(int\fP \fIfildes\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fItcgetpgrp\fP() function shall return the value of the process
group ID of the foreground process group associated with
the terminal.
.LP
If there is no foreground process group, \fItcgetpgrp\fP() shall return
a value greater than 1 that does not match the process
group ID of any existing process group.
.LP
The \fItcgetpgrp\fP() function is allowed from a process that is a
member of a background process group; however, the
information may be subsequently changed by a process that is a member
of a foreground process group.
.SH RETURN VALUE
.LP
Upon successful completion, \fItcgetpgrp\fP() shall return the value
of the process group ID of the foreground process
associated with the terminal. Otherwise, -1 shall be returned and
\fIerrno\fP set to indicate the error.
.SH ERRORS
.LP
The \fItcgetpgrp\fP() function shall fail if:
.TP 7
.B EBADF
The \fIfildes\fP argument is not a valid file descriptor.
.TP 7
.B ENOTTY
The calling process does not have a controlling terminal, or the file
is not the controlling terminal.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIsetsid\fP() , \fIsetpgid\fP() , \fItcsetpgrp\fP() , the Base Definitions
volume of IEEE\ Std\ 1003.1-2001, \fI<sys/types.h>\fP, \fI<unistd.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
