.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "ULIMIT" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" ulimit 
.SH NAME
ulimit \- get and set process limits
.SH SYNOPSIS
.LP
\fB#include <ulimit.h>
.br
.sp
long ulimit(int\fP \fIcmd\fP\fB, ...); \fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The \fIulimit\fP() function shall control process limits. The process
limits that can be controlled by this function include
the maximum size of a single file that can be written (this is equivalent
to using \fIsetrlimit\fP() with RLIMIT_FSIZE). The \fIcmd\fP values,
defined in \fI<ulimit.h>\fP, include:
.TP 7
UL_GETFSIZE
Return the file size limit (RLIMIT_FSIZE) of the process. The limit
shall be in units of 512-byte blocks and shall be inherited
by child processes. Files of any size can be read. The return value
shall be the integer part of the soft file size limit divided
by 512. If the result cannot be represented as a \fBlong\fP, the result
is unspecified.
.TP 7
UL_SETFSIZE
Set the file size limit for output operations of the process to the
value of the second argument, taken as a \fBlong\fP,
multiplied by 512. If the result would overflow an \fBrlim_t\fP, the
actual value set is unspecified. Any process may decrease its
own limit, but only a process with appropriate privileges may increase
the limit. The return value shall be the integer part of the
new file size limit divided by 512.
.sp
.LP
The \fIulimit\fP() function shall not change the setting of \fIerrno\fP
if successful.
.LP
As all return values are permissible in a successful situation, an
application wishing to check for error situations should set
\fIerrno\fP to 0, then call \fIulimit\fP(), and, if it returns -1,
check to see if \fIerrno\fP is non-zero.
.SH RETURN VALUE
.LP
Upon successful completion, \fIulimit\fP() shall return the value
of the requested limit. Otherwise, -1 shall be returned and
\fIerrno\fP set to indicate the error.
.SH ERRORS
.LP
The \fIulimit\fP() function shall fail and the limit shall be unchanged
if:
.TP 7
.B EINVAL
The \fIcmd\fP argument is not valid.
.TP 7
.B EPERM
A process not having appropriate privileges attempts to increase its
file size limit.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIgetrlimit\fP() , \fIsetrlimit\fP() , \fIwrite\fP() , the Base Definitions
volume of IEEE\ Std\ 1003.1-2001, \fI<ulimit.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
