.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "UNAME" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" uname 
.SH NAME
uname \- get the name of the current system
.SH SYNOPSIS
.LP
\fB#include <sys/utsname.h>
.br
.sp
int uname(struct utsname *\fP\fIname\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIuname\fP() function shall store information identifying the
current system in the structure pointed to by
\fIname\fP.
.LP
The \fIuname\fP() function uses the \fButsname\fP structure defined
in \fI<sys/utsname.h>\fP.
.LP
The \fIuname\fP() function shall return a string naming the current
system in the character array \fIsysname\fP. Similarly,
\fInodename\fP shall contain the name of this node within an implementation-defined
communications network. The arrays
\fIrelease\fP and \fIversion\fP shall further identify the operating
system. The array \fImachine\fP shall contain a name that
identifies the hardware that the system is running on.
.LP
The format of each member is implementation-defined.
.SH RETURN VALUE
.LP
Upon successful completion, a non-negative value shall be returned.
Otherwise, -1 shall be returned and \fIerrno\fP set to
indicate the error.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
The inclusion of the \fInodename\fP member in this structure does
not imply that it is sufficient information for interfacing
to communications networks.
.SH RATIONALE
.LP
The values of the structure members are not constrained to have any
relation to the version of this volume of
IEEE\ Std\ 1003.1-2001 implemented in the operating system. An application
should instead depend on _POSIX_VERSION and
related constants defined in \fI<unistd.h>\fP.
.LP
This volume of IEEE\ Std\ 1003.1-2001 does not define the sizes of
the members of the structure and permits them to be
of different sizes, although most implementations define them all
to be the same size: eight bytes plus one byte for the string
terminator. That size for \fInodename\fP is not enough for use with
many networks.
.LP
The \fIuname\fP() function originated in System III, System V, and
related implementations, and it does not exist in Version 7
or 4.3 BSD. The values it returns are set at system compile time in
those historical implementations.
.LP
4.3 BSD has \fIgethostname\fP() and \fIgethostid\fP(), which return
a symbolic name and a numeric value, respectively. There are
related \fIsethostname\fP() and \fIsethostid\fP() functions that are
used to set the values the other two functions return. The
former functions are included in this specification, the latter are
not.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
The Base Definitions volume of IEEE\ Std\ 1003.1-2001, \fI<sys/utsname.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
