.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "UTIMES" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" utimes 
.SH NAME
utimes \- set file access and modification times (\fBLEGACY\fP)
.SH SYNOPSIS
.LP
\fB#include <sys/time.h>
.br
.sp
int utimes(const char *\fP\fIpath\fP\fB, const struct timeval\fP \fItimes[2]\fP\fB);
\fP
\fB
.br
\fP
.SH DESCRIPTION
.LP
The \fIutimes\fP() function shall set the access and modification
times of the file pointed to by the \fIpath\fP argument to
the value of the \fItimes\fP argument. The \fIutimes\fP() function
allows time specifications accurate to the microsecond.
.LP
For \fIutimes\fP(), the \fItimes\fP argument is an array of \fBtimeval\fP
structures. The first array member represents the
date and time of last access, and the second member represents the
date and time of last modification. The times in the
\fBtimeval\fP structure are measured in seconds and microseconds since
the Epoch, although rounding toward the nearest second may
occur.
.LP
If the \fItimes\fP argument is a null pointer, the access and modification
times of the file shall be set to the current time.
The effective user ID of the process shall match the owner of the
file, or has write access to the file or appropriate privileges
to use this call in this manner. Upon completion, \fIutimes\fP() shall
mark the time of the last file status change,
\fIst_ctime\fP, for update.
.SH RETURN VALUE
.LP
Upon successful completion, 0 shall be returned. Otherwise, -1 shall
be returned and \fIerrno\fP shall be set to indicate the
error, and the file times shall not be affected.
.SH ERRORS
.LP
The \fIutimes\fP() function shall fail if:
.TP 7
.B EACCES
Search permission is denied by a component of the path prefix; or
the \fItimes\fP argument is a null pointer and the effective
user ID of the process does not match the owner of the file and write
access is denied.
.TP 7
.B ELOOP
A loop exists in symbolic links encountered during resolution of the
\fIpath\fP argument.
.TP 7
.B ENAMETOOLONG
The length of the \fIpath\fP argument exceeds {PATH_MAX} or a pathname
component is longer than {NAME_MAX}.
.TP 7
.B ENOENT
A component of \fIpath\fP does not name an existing file or \fIpath\fP
is an empty string.
.TP 7
.B ENOTDIR
A component of the path prefix is not a directory.
.TP 7
.B EPERM
The \fItimes\fP argument is not a null pointer and the calling process'
effective user ID has write access to the file but
does not match the owner of the file and the calling process does
not have the appropriate privileges.
.TP 7
.B EROFS
The file system containing the file is read-only.
.sp
.LP
The \fIutimes\fP() function may fail if:
.TP 7
.B ELOOP
More than {SYMLOOP_MAX} symbolic links were encountered during resolution
of the \fIpath\fP argument.
.TP 7
.B ENAMETOOLONG
Pathname resolution of a symbolic link produced an intermediate result
whose length exceeds {PATH_MAX}.
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
For applications portability, the \fIutime\fP() function should be
used to set file
access and modification times instead of \fIutimes\fP().
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
This function may be withdrawn in a future version.
.SH SEE ALSO
.LP
\fIutime\fP() , the Base Definitions volume of IEEE\ Std\ 1003.1-2001,
\fI<sys/time.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
