.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "WCTRANS" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" wctrans 
.SH NAME
wctrans \- define character mapping
.SH SYNOPSIS
.LP
\fB#include <wctype.h>
.br
.sp
wctrans_t wctrans(const char *\fP\fIcharclass\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIwctrans\fP() function is defined for valid character mapping
names identified in the current locale. The
\fIcharclass\fP is a string identifying a generic character mapping
name for which codeset-specific information is required. The
following character mapping names are defined in all locales: \fBtolower\fP
and \fBtoupper\fP.
.LP
The function shall return a value of type \fBwctrans_t\fP, which can
be used as the second argument to subsequent calls of \fItowctrans\fP().
The \fIwctrans\fP() function shall determine values of \fBwctrans_t\fP
according to the rules of the coded character set defined by character
mapping information in the program's locale (category
\fILC_CTYPE ).\fP The values returned by \fIwctrans\fP() shall be
valid until a call to \fIsetlocale\fP() that modifies the category
\fILC_CTYPE .\fP
.SH RETURN VALUE
.LP
The \fIwctrans\fP() function shall return 0   \ and may set \fIerrno\fP
to indicate the error  \ if the given character mapping name is not
valid for the current
locale (category \fILC_CTYPE );\fP otherwise, it shall return a non-zero
object of type \fBwctrans_t\fP that can be used in calls
to \fItowctrans\fP().
.SH ERRORS
.LP
The \fIwctrans\fP() function may fail if:
.TP 7
.B EINVAL
The character mapping name pointed to by \fIcharclass\fP is not valid
in the current locale. 
.sp
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fItowctrans\fP() , the Base Definitions volume of IEEE\ Std\ 1003.1-2001,
\fI<wctype.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
