.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "WMEMCHR" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" wmemchr 
.SH NAME
wmemchr \- find a wide character in memory
.SH SYNOPSIS
.LP
\fB#include <wchar.h>
.br
.sp
wchar_t *wmemchr(const wchar_t *\fP\fIws\fP\fB, wchar_t\fP \fIwc\fP\fB,
size_t\fP \fIn\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIwmemchr\fP() function shall locate the first occurrence of
\fIwc\fP in the initial \fIn\fP wide characters of the
object pointed to by \fIws\fP. This function shall not be affected
by locale and all \fBwchar_t\fP values shall be treated
identically. The null wide character and \fBwchar_t\fP values not
corresponding to valid characters shall not be treated
specially.
.LP
If \fIn\fP is zero, the application shall ensure that \fIws\fP is
a valid pointer and the function behaves as if no valid
occurrence of \fIwc\fP is found.
.SH RETURN VALUE
.LP
The \fIwmemchr\fP() function shall return a pointer to the located
wide character, or a null pointer if the wide character does
not occur in the object.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIwmemcmp\fP() , \fIwmemcpy\fP() , \fIwmemmove\fP() , \fIwmemset\fP()
, the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<wchar.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
