.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved 
.TH "WMEMCMP" P 2003 "IEEE/The Open Group" "POSIX Programmer's Manual"
.\" wmemcmp 
.SH NAME
wmemcmp \- compare wide characters in memory
.SH SYNOPSIS
.LP
\fB#include <wchar.h>
.br
.sp
int wmemcmp(const wchar_t *\fP\fIws1\fP\fB, const wchar_t *\fP\fIws2\fP\fB,
size_t\fP \fIn\fP\fB);
.br
\fP
.SH DESCRIPTION
.LP
The \fIwmemcmp\fP() function shall compare the first \fIn\fP wide
characters of the object pointed to by \fIws1\fP to the
first \fIn\fP wide characters of the object pointed to by \fIws2\fP.
This function shall not be affected by locale and all
\fBwchar_t\fP values shall be treated identically. The null wide character
and \fBwchar_t\fP values not corresponding to valid
characters shall not be treated specially.
.LP
If \fIn\fP is zero, the application shall ensure that \fIws1\fP and
\fIws2\fP are valid pointers, and the function shall
behave as if the two objects compare equal.
.SH RETURN VALUE
.LP
The \fIwmemcmp\fP() function shall return an integer greater than,
equal to, or less than zero, respectively, as the object
pointed to by \fIws1\fP is greater than, equal to, or less than the
object pointed to by \fIws2\fP.
.SH ERRORS
.LP
No errors are defined.
.LP
\fIThe following sections are informative.\fP
.SH EXAMPLES
.LP
None.
.SH APPLICATION USAGE
.LP
None.
.SH RATIONALE
.LP
None.
.SH FUTURE DIRECTIONS
.LP
None.
.SH SEE ALSO
.LP
\fIwmemchr\fP() , \fIwmemcpy\fP() , \fIwmemmove\fP() , \fIwmemset\fP()
, the Base Definitions volume of
IEEE\ Std\ 1003.1-2001, \fI<wchar.h>\fP
.SH COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
